( mkdir -p 'testgen/mvnc/com/google/auto/auto-common/1.2.1' && cd 'testgen/mvnc/com/google/auto/auto-common/1.2.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.auto.common.BasicAnnotationProcessor' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.auto.common.BasicAnnotationProcessor.log'
)
( mkdir -p 'testgen/mvnc/com/google/auto/auto-common/1.2.2' && cd 'testgen/mvnc/com/google/auto/auto-common/1.2.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.auto.common.BasicAnnotationProcessor' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.auto.common.BasicAnnotationProcessor.log'
)
( mkdir -p 'testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && cd 'testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.collect.testing.AbstractIteratorTester' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.collect.testing.AbstractIteratorTester.log'
)
( mkdir -p 'testgen/mvnc/com/google/guava/guava/31.0.1-jre' && cd 'testgen/mvnc/com/google/guava/guava/31.0.1-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.collect.MapMakerInternalMap' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.collect.MapMakerInternalMap.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.io.ByteSink' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.io.ByteSink.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.math.ToDoubleRounder' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.math.ToDoubleRounder.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.reflect.TypeVisitor' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.reflect.TypeVisitor.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.util.concurrent.AbstractExecutionThreadService' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.util.concurrent.AbstractExecutionThreadService.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.util.concurrent.AbstractIdleService' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.util.concurrent.AbstractIdleService.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.util.concurrent.AbstractService' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.util.concurrent.AbstractService.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.util.concurrent.InterruptibleTask' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.util.concurrent.InterruptibleTask.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'com.google.common.util.concurrent.WrappingExecutorService' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.com.google.common.util.concurrent.WrappingExecutorService.log'
)
( mkdir -p 'testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final' && cd 'testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'io.netty.handler.codec.http.LastHttpContent' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.io.netty.handler.codec.http.LastHttpContent.log'
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'io.netty.handler.codec.spdy.SpdyHeaders' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.io.netty.handler.codec.spdy.SpdyHeaders.log'
)
( mkdir -p 'testgen/mvnc/junit/junit/4.13.2' && cd 'testgen/mvnc/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'junit.runner.BaseTestRunner' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.junit.runner.BaseTestRunner.log'
)
( mkdir -p 'testgen/mvnc/org/threeten/threetenbp/1.6.6' && cd 'testgen/mvnc/org/threeten/threetenbp/1.6.6' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'org.threeten.bp.temporal.IsoFields' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.org.threeten.bp.temporal.IsoFields.log'
)
( mkdir -p 'testgen/mvnc/org/threeten/threetenbp/1.6.7' && cd 'testgen/mvnc/org/threeten/threetenbp/1.6.7' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/target t
time java -jar /home/wtwhite/code/regression-test-generation/evosuite/evosuite-1.2.0.jar -Dsearch_budget=600 -class 'org.threeten.bp.temporal.IsoFields' -projectCP /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g') 2>&1 | tee 'evosuite.org.threeten.bp.temporal.IsoFields.log'
)
