/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 10 23:57:43 GMT 2024
 */

package org.apache.hadoop.hdfs.protocol.proto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.SequenceInputStream;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.Collection;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Vector;
import org.apache.hadoop.fs.FSDataInputStream;
import org.apache.hadoop.hdfs.protocol.BlockListAsLongs;
import org.apache.hadoop.hdfs.protocol.proto.HdfsServerProtos;
import org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.thirdparty.protobuf.ByteString;
import org.apache.hadoop.thirdparty.protobuf.CodedInputStream;
import org.apache.hadoop.thirdparty.protobuf.DescriptorProtos;
import org.apache.hadoop.thirdparty.protobuf.Descriptors;
import org.apache.hadoop.thirdparty.protobuf.ExtensionRegistry;
import org.apache.hadoop.thirdparty.protobuf.ExtensionRegistryLite;
import org.apache.hadoop.thirdparty.protobuf.Field;
import org.apache.hadoop.thirdparty.protobuf.Message;
import org.apache.hadoop.thirdparty.protobuf.Parser;
import org.apache.hadoop.thirdparty.protobuf.RpcChannel;
import org.apache.hadoop.thirdparty.protobuf.UnknownFieldSet;
import org.eclipse.jetty.io.ArrayByteBufferPool;
import org.eclipse.jetty.io.ByteBufferPool;
import org.eclipse.jetty.io.LeakTrackingByteBufferPool;
import org.eclipse.jetty.io.NullByteBufferPool;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NamenodeProtocolProtos_ESTest extends NamenodeProtocolProtos_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byteArrayInputStream0.read(byteArray0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto namenodeProtocolProtos_GetMostRecentCheckpointTxIdResponseProto0 = NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseDelimitedFrom((InputStream) byteArrayInputStream0, extensionRegistryLite0);
      assertNull(namenodeProtocolProtos_GetMostRecentCheckpointTxIdResponseProto0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      NamenodeProtocolProtos.GetNextSPSPathResponseProto.Builder namenodeProtocolProtos_GetNextSPSPathResponseProto_Builder0 = NamenodeProtocolProtos.GetNextSPSPathResponseProto.newBuilder();
      assertEquals(0L, namenodeProtocolProtos_GetNextSPSPathResponseProto_Builder0.getSpsPath());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      NamenodeProtocolProtos.GetBlockKeysResponseProto.Builder namenodeProtocolProtos_GetBlockKeysResponseProto_Builder0 = NamenodeProtocolProtos.GetBlockKeysResponseProto.newBuilder();
      assertFalse(namenodeProtocolProtos_GetBlockKeysResponseProto_Builder0.hasKeys());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      NamenodeProtocolProtos.ErrorReportRequestProto namenodeProtocolProtos_ErrorReportRequestProto0 = NamenodeProtocolProtos.ErrorReportRequestProto.getDefaultInstance();
      assertEquals(1, NamenodeProtocolProtos.ErrorReportRequestProto.REGISTRATION_FIELD_NUMBER);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte) (-77);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseDelimitedFrom((InputStream) byteArrayInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte) (-77);
      byteArray0[2] = (byte) (-38);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseDelimitedFrom((InputStream) byteArrayInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: txId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeResponseProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.newBuilder((NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos$GetMostRecentCheckpointTxIdResponseProto$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      ByteBuffer byteBuffer0 = Text.encode("n{zIVHUFw", false);
      try { 
        NamenodeProtocolProtos.GetNextSPSPathRequestProto.parseFrom(byteBuffer0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte) (-16);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseFrom(byteArray0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte) (-24);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetFilePathResponseProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte) (-12);
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeRequestProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message end-group tag did not match expected tag.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte) (-111);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetEditLogManifestRequestProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte) (-26);
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance(byteArray0);
      try { 
        NamenodeProtocolProtos.EndCheckpointRequestProto.parseFrom(codedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte)23;
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      try { 
        NamenodeProtocolProtos.StartCheckpointRequestProto.parseFrom(byteBuffer0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)127;
      try { 
        NamenodeProtocolProtos.RegisterResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)86;
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.RegisterRequestProto.parseFrom(byteArray0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      NamenodeProtocolProtos.ErrorReportResponseProto.Builder namenodeProtocolProtos_ErrorReportResponseProto_Builder0 = NamenodeProtocolProtos.ErrorReportResponseProto.newBuilder();
      NamenodeProtocolProtos.ErrorReportResponseProto namenodeProtocolProtos_ErrorReportResponseProto0 = NamenodeProtocolProtos.ErrorReportResponseProto.getDefaultInstance();
      NamenodeProtocolProtos.ErrorReportResponseProto.Builder namenodeProtocolProtos_ErrorReportResponseProto_Builder1 = namenodeProtocolProtos_ErrorReportResponseProto_Builder0.mergeFrom(namenodeProtocolProtos_ErrorReportResponseProto0);
      assertSame(namenodeProtocolProtos_ErrorReportResponseProto_Builder1, namenodeProtocolProtos_ErrorReportResponseProto_Builder0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      NamenodeProtocolProtos.ErrorReportRequestProto.Builder namenodeProtocolProtos_ErrorReportRequestProto_Builder0 = NamenodeProtocolProtos.ErrorReportRequestProto.newBuilder();
      NamenodeProtocolProtos.ErrorReportRequestProto.Builder namenodeProtocolProtos_ErrorReportRequestProto_Builder1 = namenodeProtocolProtos_ErrorReportRequestProto_Builder0.clearRegistration();
      assertFalse(namenodeProtocolProtos_ErrorReportRequestProto_Builder1.hasErrorCode());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte)102;
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.ErrorReportRequestProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      NamenodeProtocolProtos.RollEditLogResponseProto.Builder namenodeProtocolProtos_RollEditLogResponseProto_Builder0 = NamenodeProtocolProtos.RollEditLogResponseProto.newBuilder();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_RollEditLogResponseProto_Builder0.mergeFrom((Message) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractMessage$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0 = NamenodeProtocolProtos.GetTransactionIdResponseProto.newBuilder();
      NamenodeProtocolProtos.GetTransactionIdResponseProto namenodeProtocolProtos_GetTransactionIdResponseProto0 = NamenodeProtocolProtos.GetTransactionIdResponseProto.getDefaultInstance();
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1 = namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0.mergeFrom(namenodeProtocolProtos_GetTransactionIdResponseProto0);
      assertFalse(namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1.hasTxId());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte) (-2);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      try { 
        NamenodeProtocolProtos.GetBlockKeysRequestProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message tag had invalid wire type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      NamenodeProtocolProtos.IsRollingUpgradeResponseProto.Builder namenodeProtocolProtos_IsRollingUpgradeResponseProto_Builder0 = NamenodeProtocolProtos.IsRollingUpgradeResponseProto.newBuilder();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_IsRollingUpgradeResponseProto_Builder0.addRepeatedField((Descriptors.FieldDescriptor) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      try { 
        NamenodeProtocolProtos.StartCheckpointResponseProto.parseFrom((InputStream) null);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: command
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.StartCheckpointResponseProto.getDescriptor();
      assertFalse(descriptors_Descriptor0.isExtendable());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      ByteString byteString0 = ByteString.copyFrom("ED-U;", charset0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.StartCheckpointResponseProto.parseFrom(byteString0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: command
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.StartCheckpointResponseProto.parseDelimitedFrom((InputStream) null, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(77);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeResponseProto.parseFrom(byteBuffer0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte) (-3);
      byteArray0[6] = (byte) (-124);
      byteArray0[7] = (byte)106;
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance(byteArray0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeResponseProto.parseFrom(codedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: isRollingUpgrade
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.RollEditLogResponseProto.parseFrom((ByteString) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      try { 
        NamenodeProtocolProtos.RollEditLogResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      try { 
        NamenodeProtocolProtos.StartCheckpointRequestProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseFrom((InputStream) pipedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseFrom((ByteString) null, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      try { 
        NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      NamenodeProtocolProtos.GetNextSPSPathResponseProto namenodeProtocolProtos_GetNextSPSPathResponseProto0 = NamenodeProtocolProtos.GetNextSPSPathResponseProto.getDefaultInstance();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_GetNextSPSPathResponseProto0.getOneofFieldDescriptor((Descriptors.OneofDescriptor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3$FieldAccessorTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      NamenodeProtocolProtos.GetNextSPSPathResponseProto namenodeProtocolProtos_GetNextSPSPathResponseProto0 = NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseFrom((InputStream) null);
      assertEquals(0L, namenodeProtocolProtos_GetNextSPSPathResponseProto0.getSpsPath());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream((InputStream) null);
      try { 
        NamenodeProtocolProtos.GetNextSPSPathResponseProto.parseDelimitedFrom((InputStream) bufferedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream closed
         //
         verifyException("java.io.BufferedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(45335656);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      try { 
        NamenodeProtocolProtos.ErrorReportRequestProto.parseFrom(byteBuffer0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      NamenodeProtocolProtos.GetBlockKeysRequestProto namenodeProtocolProtos_GetBlockKeysRequestProto0 = NamenodeProtocolProtos.GetBlockKeysRequestProto.parseFrom((InputStream) null);
      assertNotNull(namenodeProtocolProtos_GetBlockKeysRequestProto0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto namenodeProtocolProtos_IsUpgradeFinalizedResponseProto0 = NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.getDefaultInstance();
      assertFalse(namenodeProtocolProtos_IsUpgradeFinalizedResponseProto0.hasIsUpgradeFinalized());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      LeakTrackingByteBufferPool leakTrackingByteBufferPool0 = new LeakTrackingByteBufferPool((ByteBufferPool) null);
      Class<ByteString> class0 = ByteString.class;
      Collection<ByteString> collection0 = leakTrackingByteBufferPool0.getContainedBeans(class0);
      PriorityQueue<ByteString> priorityQueue0 = new PriorityQueue<ByteString>(collection0);
      ByteString byteString0 = ByteString.copyFrom((Iterable<ByteString>) priorityQueue0);
      try { 
        NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.parseFrom(byteString0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: isUpgradeFinalized
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance((byte[]) null, 929, 4485);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.parseFrom(codedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.CodedInputStream$ArrayDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Vector<ByteString> vector0 = new Vector<ByteString>();
      BlockListAsLongs blockListAsLongs0 = BlockListAsLongs.decodeBuffers((-45), (List<ByteString>) vector0);
      ByteString byteString0 = blockListAsLongs0.getBlocksBuffer();
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetFilePathRequestProto.parseFrom(byteString0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: fileId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetFilePathRequestProto.parseDelimitedFrom((InputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Vector<ByteString> vector0 = new Vector<ByteString>();
      BlockListAsLongs blockListAsLongs0 = BlockListAsLongs.decodeBuffers((-45), (List<ByteString>) vector0);
      ByteString byteString0 = blockListAsLongs0.getBlocksBuffer();
      try { 
        NamenodeProtocolProtos.GetFilePathRequestProto.parseFrom(byteString0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: fileId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetFilePathRequestProto.parseFrom((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.Builder namenodeProtocolProtos_IsUpgradeFinalizedResponseProto_Builder0 = NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.newBuilder();
      NamenodeProtocolProtos.IsUpgradeFinalizedResponseProto.Builder namenodeProtocolProtos_IsUpgradeFinalizedResponseProto_Builder1 = namenodeProtocolProtos_IsUpgradeFinalizedResponseProto_Builder0.clear();
      assertFalse(namenodeProtocolProtos_IsUpgradeFinalizedResponseProto_Builder1.getIsUpgradeFinalized());
      assertFalse(namenodeProtocolProtos_IsUpgradeFinalizedResponseProto_Builder1.isInitialized());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0 = NamenodeProtocolProtos.GetTransactionIdResponseProto.newBuilder();
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1 = namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0.clear();
      assertEquals(0L, namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1.getTxId());
      assertFalse(namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1.hasTxId());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0 = NamenodeProtocolProtos.GetTransactionIdResponseProto.newBuilder();
      String string0 = namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(127);
      ByteString byteString0 = ByteString.copyFrom(byteBuffer0, 8);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      try { 
        NamenodeProtocolProtos.GetBlockKeysResponseProto.parseFrom(byteString0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      NamenodeProtocolProtos.GetBlockKeysResponseProto namenodeProtocolProtos_GetBlockKeysResponseProto0 = NamenodeProtocolProtos.GetBlockKeysResponseProto.getDefaultInstance();
      HdfsServerProtos.ExportedBlockKeysProto hdfsServerProtos_ExportedBlockKeysProto0 = namenodeProtocolProtos_GetBlockKeysResponseProto0.getKeys();
      assertFalse(hdfsServerProtos_ExportedBlockKeysProto0.hasKeyUpdateInterval());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Parser<NamenodeProtocolProtos.GetBlockKeysResponseProto> parser0 = NamenodeProtocolProtos.GetBlockKeysResponseProto.parser();
      assertNotNull(parser0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      try { 
        NamenodeProtocolProtos.RegisterResponseProto.parseFrom((InputStream) null);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: registration
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.RegisterResponseProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.ErrorReportRequestProto.Builder.getDescriptor();
      assertFalse(descriptors_Descriptor0.isExtendable());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      NamenodeProtocolProtos.ErrorReportRequestProto.Builder namenodeProtocolProtos_ErrorReportRequestProto_Builder0 = NamenodeProtocolProtos.ErrorReportRequestProto.newBuilder();
      NamenodeProtocolProtos.ErrorReportRequestProto.Builder namenodeProtocolProtos_ErrorReportRequestProto_Builder1 = namenodeProtocolProtos_ErrorReportRequestProto_Builder0.clone();
      assertFalse(namenodeProtocolProtos_ErrorReportRequestProto_Builder1.hasMsg());
      assertFalse(namenodeProtocolProtos_ErrorReportRequestProto_Builder1.hasRegistration());
      assertFalse(namenodeProtocolProtos_ErrorReportRequestProto_Builder1.hasErrorCode());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.EndCheckpointRequestProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance((InputStream) null, 12669);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.EndCheckpointRequestProto.parseFrom(codedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: registration, signature
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      ByteString byteString0 = ByteString.EMPTY;
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      try { 
        NamenodeProtocolProtos.EndCheckpointRequestProto.parseFrom(byteString0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: registration, signature
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.GetBlockKeysResponseProto.Builder.getDescriptor();
      assertEquals("hadoop.hdfs.namenode.GetBlockKeysResponseProto", descriptors_Descriptor0.getFullName());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      NamenodeProtocolProtos.EndCheckpointResponseProto namenodeProtocolProtos_EndCheckpointResponseProto0 = NamenodeProtocolProtos.EndCheckpointResponseProto.getDefaultInstance();
      assertNotNull(namenodeProtocolProtos_EndCheckpointResponseProto0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      UnknownFieldSet.Field unknownFieldSet_Field0 = UnknownFieldSet.Field.getDefaultInstance();
      List<Long> list0 = unknownFieldSet_Field0.getVarintList();
      BlockListAsLongs blockListAsLongs0 = BlockListAsLongs.decodeLongs(list0, 6);
      ByteString byteString0 = blockListAsLongs0.getBlocksBuffer();
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      NamenodeProtocolProtos.ErrorReportResponseProto namenodeProtocolProtos_ErrorReportResponseProto0 = NamenodeProtocolProtos.ErrorReportResponseProto.parseFrom(byteString0, extensionRegistryLite0);
      boolean boolean0 = namenodeProtocolProtos_ErrorReportResponseProto0.equals(blockListAsLongs0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(2652);
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance(byteBuffer0);
      try { 
        NamenodeProtocolProtos.ErrorReportResponseProto.parseFrom(codedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      NamenodeProtocolProtos.GetBlocksRequestProto.Builder namenodeProtocolProtos_GetBlocksRequestProto_Builder0 = NamenodeProtocolProtos.GetBlocksRequestProto.newBuilder();
      assertEquals(10485760L, namenodeProtocolProtos_GetBlocksRequestProto_Builder0.getMinBlockSize());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      try { 
        NamenodeProtocolProtos.GetBlocksRequestProto.parseDelimitedFrom((InputStream) pipedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      NamenodeProtocolProtos.EndCheckpointRequestProto namenodeProtocolProtos_EndCheckpointRequestProto0 = NamenodeProtocolProtos.EndCheckpointRequestProto.getDefaultInstance();
      NamenodeProtocolProtos.EndCheckpointRequestProto.Builder namenodeProtocolProtos_EndCheckpointRequestProto_Builder0 = NamenodeProtocolProtos.EndCheckpointRequestProto.newBuilder(namenodeProtocolProtos_EndCheckpointRequestProto0);
      NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.Builder namenodeProtocolProtos_GetMostRecentCheckpointTxIdResponseProto_Builder0 = NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.newBuilder();
      Descriptors.Descriptor descriptors_Descriptor0 = namenodeProtocolProtos_GetMostRecentCheckpointTxIdResponseProto_Builder0.getDescriptorForType();
      Descriptors.OneofDescriptor descriptors_OneofDescriptor0 = mock(Descriptors.OneofDescriptor.class, new ViolatedAssumptionAnswer());
      doReturn(descriptors_Descriptor0).when(descriptors_OneofDescriptor0).getContainingType();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_EndCheckpointRequestProto_Builder0.getOneofFieldDescriptor(descriptors_OneofDescriptor0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // OneofDescriptor does not match message type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3$FieldAccessorTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.EndCheckpointRequestProto.Builder.getDescriptor();
      assertEquals("hadoop.hdfs.namenode.EndCheckpointRequestProto", descriptors_Descriptor0.getFullName());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.GetBlocksResponseProto.Builder.getDescriptor();
      assertEquals(1, descriptors_Descriptor0.getIndex());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      try { 
        NamenodeProtocolProtos.RollEditLogRequestProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.RollEditLogRequestProto.Builder.getDescriptor();
      NamenodeProtocolProtos.GetEditLogManifestRequestProto.Builder namenodeProtocolProtos_GetEditLogManifestRequestProto_Builder0 = NamenodeProtocolProtos.GetEditLogManifestRequestProto.newBuilder();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_GetEditLogManifestRequestProto_Builder0.setField((Descriptors.FieldDescriptor) null, descriptors_Descriptor0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      NullByteBufferPool nullByteBufferPool0 = new NullByteBufferPool();
      ByteBuffer byteBuffer0 = nullByteBufferPool0.acquire(1500, false);
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseFrom(byteBuffer0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: txId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      PriorityQueue<ByteBuffer> priorityQueue0 = new PriorityQueue<ByteBuffer>();
      HashSet<ByteBuffer> hashSet0 = new HashSet<ByteBuffer>(priorityQueue0);
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance((Iterable<ByteBuffer>) hashSet0);
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseFrom(codedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: txId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetMostRecentCheckpointTxIdResponseProto.parseFrom(byteArray0, (ExtensionRegistryLite) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos$GetMostRecentCheckpointTxIdResponseProto$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Parser<NamenodeProtocolProtos.GetFilePathResponseProto> parser0 = NamenodeProtocolProtos.GetFilePathResponseProto.parser();
      assertNotNull(parser0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Field field0 = Field.getDefaultInstance();
      ByteString byteString0 = field0.getDefaultValueBytes();
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetFilePathResponseProto.parseFrom(byteString0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: srcPath
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      try { 
        NamenodeProtocolProtos.GetFilePathResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      DescriptorProtos.FileDescriptorProto descriptorProtos_FileDescriptorProto0 = DescriptorProtos.FileDescriptorProto.getDefaultInstance();
      DescriptorProtos.FileOptions descriptorProtos_FileOptions0 = descriptorProtos_FileDescriptorProto0.getOptions();
      ByteString byteString0 = descriptorProtos_FileOptions0.getGoPackageBytes();
      CodedInputStream codedInputStream0 = byteString0.newCodedInput();
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetFilePathResponseProto.parseFrom(codedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: srcPath
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      NamenodeProtocolProtos.GetNextSPSPathResponseProto namenodeProtocolProtos_GetNextSPSPathResponseProto0 = NamenodeProtocolProtos.GetNextSPSPathResponseProto.getDefaultInstance();
      NamenodeProtocolProtos.GetNextSPSPathResponseProto.Builder namenodeProtocolProtos_GetNextSPSPathResponseProto_Builder0 = namenodeProtocolProtos_GetNextSPSPathResponseProto0.toBuilder();
      Descriptors.Descriptor descriptors_Descriptor0 = HdfsServerProtos.StorageInfoProto.getDescriptor();
      Descriptors.FieldDescriptor descriptors_FieldDescriptor0 = descriptors_Descriptor0.findFieldByNumber(1);
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_GetNextSPSPathResponseProto_Builder0.setField(descriptors_FieldDescriptor0, extensionRegistryLite0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // FieldDescriptor does not match message type.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3$FieldAccessorTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      NamenodeProtocolProtos.StartCheckpointResponseProto.Builder namenodeProtocolProtos_StartCheckpointResponseProto_Builder0 = NamenodeProtocolProtos.StartCheckpointResponseProto.newBuilder();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_StartCheckpointResponseProto_Builder0.clearOneof((Descriptors.OneofDescriptor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.GeneratedMessageV3$FieldAccessorTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetEditLogManifestRequestProto.parseFrom((ByteString) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.AbstractParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance((InputStream) null);
      try { 
        NamenodeProtocolProtos.GetEditLogManifestRequestProto.parseFrom(codedInputStream0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: sinceTxId
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Parser<NamenodeProtocolProtos.GetEditLogManifestRequestProto> parser0 = NamenodeProtocolProtos.GetEditLogManifestRequestProto.parser();
      assertNotNull(parser0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      try { 
        NamenodeProtocolProtos.GetEditLogManifestRequestProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0 = NamenodeProtocolProtos.GetTransactionIdResponseProto.newBuilder();
      ByteBuffer byteBuffer0 = Text.encode("", false);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.getEmptyRegistry();
      HdfsServerProtos.RemoteEditLogManifestProto hdfsServerProtos_RemoteEditLogManifestProto0 = HdfsServerProtos.RemoteEditLogManifestProto.parseFrom(byteBuffer0, (ExtensionRegistryLite) extensionRegistry0);
      UnknownFieldSet unknownFieldSet0 = hdfsServerProtos_RemoteEditLogManifestProto0.getUnknownFields();
      NamenodeProtocolProtos.GetTransactionIdResponseProto.Builder namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1 = namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0.setUnknownFields(unknownFieldSet0);
      assertSame(namenodeProtocolProtos_GetTransactionIdResponseProto_Builder0, namenodeProtocolProtos_GetTransactionIdResponseProto_Builder1);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      NamenodeProtocolProtos.GetEditLogManifestResponseProto namenodeProtocolProtos_GetEditLogManifestResponseProto0 = NamenodeProtocolProtos.GetEditLogManifestResponseProto.getDefaultInstance();
      NamenodeProtocolProtos.GetEditLogManifestResponseProto.Builder namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder0 = NamenodeProtocolProtos.GetEditLogManifestResponseProto.newBuilder(namenodeProtocolProtos_GetEditLogManifestResponseProto0);
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder0.clearField((Descriptors.FieldDescriptor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      NamenodeProtocolProtos.GetEditLogManifestResponseProto.Builder namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder0 = NamenodeProtocolProtos.GetEditLogManifestResponseProto.newBuilder();
      NamenodeProtocolProtos.GetEditLogManifestResponseProto.Builder namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder1 = namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder0.clone();
      assertFalse(namenodeProtocolProtos_GetEditLogManifestResponseProto_Builder1.hasManifest());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      try { 
        NamenodeProtocolProtos.GetEditLogManifestResponseProto.parseFrom(byteArray0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      ByteString byteString0 = ByteString.copyFromUtf8("ModificationLabel");
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetEditLogManifestResponseProto.parseFrom(byteString0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      try { 
        NamenodeProtocolProtos.GetEditLogManifestResponseProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      ByteBuffer byteBuffer0 = Text.encode("ED-U;", false);
      NamenodeProtocolProtos.GetTransactionIdRequestProto namenodeProtocolProtos_GetTransactionIdRequestProto0 = NamenodeProtocolProtos.GetTransactionIdRequestProto.parseFrom(byteBuffer0, extensionRegistryLite0);
      assertNotNull(namenodeProtocolProtos_GetTransactionIdRequestProto0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream(1780);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.getEmptyRegistry();
      try { 
        NamenodeProtocolProtos.GetTransactionIdRequestProto.parseFrom((InputStream) pipedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      ByteString byteString0 = ByteString.copyFrom("ED-U;", charset0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      NamenodeProtocolProtos.GetTransactionIdRequestProto namenodeProtocolProtos_GetTransactionIdRequestProto0 = NamenodeProtocolProtos.GetTransactionIdRequestProto.parseFrom(byteString0, extensionRegistryLite0);
      String string0 = namenodeProtocolProtos_GetTransactionIdRequestProto0.toString();
      assertEquals("8: 0x3b552d44\n", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      byte[] byteArray0 = new byte[5];
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance(byteArray0);
      try { 
        NamenodeProtocolProtos.GetTransactionIdRequestProto.parseFrom(codedInputStream0, extensionRegistryLite0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      NamenodeProtocolProtos.GetTransactionIdRequestProto namenodeProtocolProtos_GetTransactionIdRequestProto0 = NamenodeProtocolProtos.GetTransactionIdRequestProto.getDefaultInstance();
      assertNotNull(namenodeProtocolProtos_GetTransactionIdRequestProto0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      ByteString byteString0 = ByteString.copyFrom("ED-U;", charset0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      NamenodeProtocolProtos.GetTransactionIdRequestProto namenodeProtocolProtos_GetTransactionIdRequestProto0 = NamenodeProtocolProtos.GetTransactionIdRequestProto.parseFrom(byteString0, extensionRegistryLite0);
      int int0 = namenodeProtocolProtos_GetTransactionIdRequestProto0.getSerializedSize();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Enumeration<FSDataInputStream> enumeration0 = (Enumeration<FSDataInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      ExtensionRegistryLite extensionRegistryLite0 = ExtensionRegistryLite.newInstance();
      NamenodeProtocolProtos.GetNextSPSPathRequestProto namenodeProtocolProtos_GetNextSPSPathRequestProto0 = NamenodeProtocolProtos.GetNextSPSPathRequestProto.parseDelimitedFrom((InputStream) sequenceInputStream0, extensionRegistryLite0);
      assertNull(namenodeProtocolProtos_GetNextSPSPathRequestProto0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      CodedInputStream codedInputStream0 = CodedInputStream.newInstance(byteArray0, 10, 10);
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetNextSPSPathRequestProto.parseFrom(codedInputStream0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 10
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.CodedInputStream$ArrayDecoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0 = NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto.getDefaultInstance();
      assertNotNull(namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      DescriptorProtos.FileOptions descriptorProtos_FileOptions0 = DescriptorProtos.FileOptions.getDefaultInstance();
      ByteString byteString0 = descriptorProtos_FileOptions0.getJavaOuterClassnameBytes();
      CodedInputStream codedInputStream0 = byteString0.newCodedInput();
      NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0 = NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto.parseFrom(codedInputStream0);
      assertNotNull(namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      ArrayByteBufferPool arrayByteBufferPool0 = new ArrayByteBufferPool(7, (-1480), (-1367), 1674);
      ByteBuffer byteBuffer0 = arrayByteBufferPool0.newByteBuffer(7, false);
      NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0 = NamenodeProtocolProtos.IsUpgradeFinalizedRequestProto.parseFrom(byteBuffer0);
      assertNotNull(namenodeProtocolProtos_IsUpgradeFinalizedRequestProto0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      try { 
        NamenodeProtocolProtos.IsRollingUpgradeRequestProto.parseFrom(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.IsRollingUpgradeRequestProto.Builder.getDescriptor();
      assertEquals("hadoop.hdfs.namenode.IsRollingUpgradeRequestProto", descriptors_Descriptor0.getFullName());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Descriptors.Descriptor descriptors_Descriptor0 = NamenodeProtocolProtos.RegisterRequestProto.getDescriptor();
      assertEquals("hadoop.hdfs.namenode.RegisterRequestProto", descriptors_Descriptor0.getFullName());
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      NamenodeProtocolProtos.RegisterRequestProto namenodeProtocolProtos_RegisterRequestProto0 = NamenodeProtocolProtos.RegisterRequestProto.getDefaultInstance();
      NamenodeProtocolProtos.RegisterRequestProto.Builder namenodeProtocolProtos_RegisterRequestProto_Builder0 = namenodeProtocolProtos_RegisterRequestProto0.toBuilder();
      // Undeclared exception!
      try { 
        namenodeProtocolProtos_RegisterRequestProto_Builder0.mergeFrom((CodedInputStream) null, (ExtensionRegistryLite) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos$RegisterRequestProto$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      DescriptorProtos.FileOptions descriptorProtos_FileOptions0 = DescriptorProtos.FileOptions.getDefaultInstance();
      ByteString byteString0 = descriptorProtos_FileOptions0.getJavaOuterClassnameBytes();
      CodedInputStream codedInputStream0 = byteString0.newCodedInput();
      ExtensionRegistry extensionRegistry0 = ExtensionRegistry.newInstance();
      try { 
        NamenodeProtocolProtos.RegisterRequestProto.parseFrom(codedInputStream0, (ExtensionRegistryLite) extensionRegistry0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Message missing required fields: registration
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.UninitializedMessageException", e);
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      // Undeclared exception!
      try { 
        NamenodeProtocolProtos.GetBlocksResponseProto.newBuilder((NamenodeProtocolProtos.GetBlocksResponseProto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.hadoop.hdfs.protocol.proto.NamenodeProtocolProtos$GetBlocksResponseProto$Builder", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(10);
      try { 
        NamenodeProtocolProtos.GetBlocksResponseProto.parseFrom(byteBuffer0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Protocol message contained an invalid tag (zero).
         //
         verifyException("org.apache.hadoop.thirdparty.protobuf.InvalidProtocolBufferException", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      NamenodeProtocolProtos.NamenodeProtocolService.Stub namenodeProtocolProtos_NamenodeProtocolService_Stub0 = NamenodeProtocolProtos.NamenodeProtocolService.newStub((RpcChannel) null);
      assertNotNull(namenodeProtocolProtos_NamenodeProtocolService_Stub0);
  }
}
