/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Nov 08 03:57:52 GMT 2024
 */

package io.restassured.internal;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class RedirectSpecificationImpl_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "io.restassured.internal.RedirectSpecificationImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("user.dir", "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RedirectSpecificationImpl_ESTest_scaffolding.class.getClassLoader() ,
      "io.restassured.config.LogConfig",
      "org.apache.http.client.methods.HttpPost",
      "org.apache.http.conn.scheme.LayeredSocketFactory",
      "org.apache.http.client.methods.HttpPatch",
      "io.restassured.config.HttpClientConfig$1",
      "io.restassured.http.Header",
      "io.restassured.config.HttpClientConfig$2",
      "io.restassured.config.DecoderConfig$1",
      "io.restassured.http.Cookies",
      "io.restassured.specification.ResponseLogSpecification",
      "io.restassured.internal.RestAssuredResponseImpl",
      "org.apache.commons.lang3.StringUtils",
      "io.restassured.config.MatcherConfig$ErrorDescriptionType",
      "io.restassured.response.Validatable",
      "io.restassured.path.json.mapper.factory.DefaultJackson1ObjectMapperFactory",
      "io.restassured.internal.http.HttpResponseContentTypeFinder",
      "org.codehaus.jackson.JsonGenerator",
      "io.restassured.internal.RestAssuredResponseOptionsImpl",
      "io.restassured.mapper.ObjectMapperSerializationContext",
      "io.restassured.internal.support.ParameterUpdater",
      "org.apache.http.conn.ssl.SSLSocketFactory",
      "org.apache.http.HttpMessage",
      "io.restassured.config.MatcherConfig",
      "io.restassured.internal.http.HTTPBuilder$RequestConfigDelegate",
      "io.restassured.config.FailureConfig",
      "io.restassured.specification.RequestLogSpecification",
      "io.restassured.config.ObjectMapperConfig",
      "org.apache.http.conn.HttpInetSocketAddress",
      "io.restassured.authentication.BasicAuthScheme",
      "io.restassured.config.RedirectConfig",
      "org.apache.http.conn.scheme.SchemeSocketFactory",
      "io.restassured.config.HeaderConfig$1",
      "org.apache.johnzon.mapper.Mapper",
      "io.restassured.specification.RequestSenderOptions",
      "io.restassured.response.ResponseBody",
      "io.restassured.config.EncoderConfig$1",
      "io.restassured.config.JsonConfig",
      "io.restassured.config.MultiPartConfig",
      "org.apache.http.HttpRequest",
      "io.restassured.authentication.AuthenticationScheme",
      "io.restassured.config.SSLConfig",
      "org.apache.http.conn.ssl.AllowAllHostnameVerifier",
      "io.restassured.response.ResponseBodyExtractionOptions",
      "io.restassured.config.Config",
      "org.apache.http.conn.socket.ConnectionSocketFactory",
      "io.restassured.common.mapper.factory.ObjectMapperFactory",
      "io.restassured.config.HeaderConfig",
      "io.restassured.internal.common.classpath.ClassPathResolver",
      "io.restassured.config.HttpClientConfig",
      "org.apache.http.client.ClientProtocolException",
      "org.codehaus.jackson.Versioned",
      "io.restassured.specification.MultiPartSpecification",
      "io.restassured.path.json.mapper.factory.DefaultGsonObjectMapperFactory",
      "org.apache.http.client.methods.Configurable",
      "io.restassured.common.mapper.resolver.ObjectMapperResolver",
      "com.fasterxml.jackson.core.JsonGenerator",
      "io.restassured.http.Cookie",
      "io.restassured.path.json.mapper.factory.Jackson1ObjectMapperFactory",
      "jakarta.xml.bind.Binder",
      "io.restassured.path.xml.mapper.factory.JakartaEEObjectMapperFactory",
      "com.fasterxml.jackson.core.ObjectCodec",
      "org.apache.http.client.methods.HttpUriRequest",
      "io.restassured.internal.NoParameterValue",
      "io.restassured.path.json.mapper.factory.JsonbObjectMapperFactory",
      "io.restassured.config.DecoderConfig",
      "io.restassured.listener.ResponseValidationFailureListener",
      "io.restassured.http.Headers",
      "org.hamcrest.TypeSafeDiagnosingMatcher",
      "io.restassured.specification.ProxySpecification",
      "org.hamcrest.BaseMatcher",
      "org.apache.http.conn.ssl.AbstractVerifier",
      "io.restassured.path.json.JsonPath",
      "org.apache.http.conn.ConnectTimeoutException",
      "io.restassured.config.HttpClientConfig$HttpClientFactory",
      "org.apache.http.client.methods.AbortableHttpRequest",
      "io.restassured.response.ValidatableResponseOptions",
      "org.apache.http.client.HttpClient",
      "io.restassured.internal.common.assertion.AssertParameter",
      "org.apache.http.client.methods.AbstractExecutionAwareRequest",
      "io.restassured.path.xml.config.XmlPathConfig",
      "io.restassured.config.RestAssuredConfig",
      "io.restassured.internal.http.HttpResponseException",
      "io.restassured.path.xml.mapper.factory.DefaultJakartaEEObjectMapperFactory",
      "com.fasterxml.jackson.core.TreeCodec",
      "io.restassured.authentication.CertAuthScheme",
      "io.restassured.config.ParamConfig",
      "org.apache.http.entity.mime.HttpMultipartMode",
      "io.restassured.internal.RequestSpecificationImpl$EncodingTarget",
      "org.apache.commons.lang3.Validate",
      "org.apache.http.protocol.HttpContext",
      "org.apache.http.params.HttpParams",
      "org.hamcrest.Matcher",
      "org.apache.http.HttpResponse",
      "io.restassured.http.Method",
      "io.restassured.mapper.ObjectMapperDeserializationContext",
      "io.restassured.internal.RestAssuredHttpBuilder",
      "io.restassured.internal.http.HttpResponseDecorator",
      "org.apache.http.HttpHost",
      "org.codehaus.jackson.map.ObjectMapper",
      "io.restassured.mapper.ObjectMapper",
      "io.restassured.common.mapper.ObjectDeserializationContext",
      "io.restassured.config.ConnectionConfig",
      "org.apache.http.client.methods.HttpEntityEnclosingRequestBase",
      "io.restassured.path.json.config.JsonPathConfig$NumberReturnType",
      "org.apache.http.client.params.ClientPNames",
      "io.restassured.internal.RedirectSpecificationImpl",
      "com.fasterxml.jackson.core.Versioned",
      "org.apache.http.conn.scheme.LayeredSchemeSocketFactory",
      "io.restassured.specification.RedirectSpecification",
      "io.restassured.path.json.mapper.factory.Jackson2ObjectMapperFactory",
      "org.apache.http.conn.scheme.SchemeLayeredSocketFactory",
      "io.restassured.parsing.Parser",
      "org.apache.http.conn.ssl.StrictHostnameVerifier",
      "io.restassured.internal.RequestSpecificationImpl",
      "io.restassured.specification.ResponseSpecification",
      "io.restassured.filter.FilterContext",
      "org.apache.http.conn.ssl.X509HostnameVerifier",
      "io.restassured.specification.RequestSpecification",
      "com.google.gson.Gson",
      "io.restassured.common.mapper.TypeRef",
      "io.restassured.specification.AuthenticationSpecification",
      "io.restassured.internal.http.HTTPBuilder",
      "io.restassured.path.xml.XmlPath",
      "io.restassured.internal.http.ContentEncodingRegistry",
      "org.eclipse.yasson.JsonBindingProvider",
      "io.restassured.internal.NameAndValue",
      "org.codehaus.jackson.ObjectCodec",
      "io.restassured.config.SessionConfig",
      "org.apache.http.client.methods.HttpRequestBase",
      "io.restassured.http.ContentType",
      "io.restassured.matcher.DetailedCookieMatcher",
      "io.restassured.internal.log.LogRepository",
      "io.restassured.internal.LogRequestAndResponseOnFailListener",
      "org.apache.http.conn.socket.LayeredConnectionSocketFactory",
      "io.restassured.response.ExtractableResponse",
      "org.apache.http.conn.ssl.BrowserCompatHostnameVerifier",
      "org.apache.http.client.methods.HttpGet",
      "org.apache.http.conn.scheme.SocketFactory",
      "io.restassured.path.xml.mapper.factory.JAXBObjectMapperFactory",
      "io.restassured.path.json.mapper.factory.JohnzonObjectMapperFactory",
      "io.restassured.config.DecoderConfig$ContentDecoder",
      "org.hamcrest.SelfDescribing",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "io.restassured.authentication.NoAuthScheme",
      "io.restassured.specification.FilterableRequestSpecification",
      "org.hamcrest.core.CombinableMatcher",
      "io.restassured.response.ResponseOptions",
      "io.restassured.response.ResponseBodyData",
      "io.restassured.path.json.mapper.factory.DefaultJohnzonObjectMapperFactory",
      "io.restassured.config.ParamConfig$UpdateStrategy",
      "io.restassured.config.EncoderConfig",
      "io.restassured.config.CsrfConfig",
      "io.restassured.path.json.mapper.factory.DefaultJackson2ObjectMapperFactory",
      "io.restassured.specification.LogSpecification",
      "io.restassured.specification.QueryableRequestSpecification",
      "org.apache.http.impl.client.AbstractHttpClient",
      "org.apache.http.message.AbstractHttpMessage",
      "io.restassured.config.OAuthConfig",
      "io.restassured.specification.RequestSender",
      "io.restassured.specification.FilterableResponseSpecification",
      "io.restassured.filter.log.LogDetail",
      "io.restassured.path.xml.mapper.factory.DefaultJAXBObjectMapperFactory",
      "org.apache.http.HttpEntityEnclosingRequest",
      "org.apache.http.impl.client.CloseableHttpClient",
      "io.restassured.config.XmlConfig",
      "io.restassured.path.xml.XmlPath$CompatibilityMode",
      "org.apache.http.client.HttpResponseException",
      "com.fasterxml.jackson.databind.ObjectMapper",
      "io.restassured.path.json.mapper.factory.DefaultYassonObjectMapperFactory",
      "org.apache.http.client.methods.HttpExecutionAware",
      "io.restassured.path.json.config.JsonPathConfig",
      "io.restassured.internal.http.ResponseParseException",
      "jakarta.xml.bind.JAXBException",
      "io.restassured.filter.Filter",
      "io.restassured.response.Response",
      "io.restassured.internal.RequestSpecificationImpl$1",
      "io.restassured.path.json.mapper.factory.GsonObjectMapperFactory",
      "io.restassured.internal.support.ParameterUpdater$Serializer",
      "io.restassured.internal.MultiValueEntity",
      "io.restassured.mapper.ObjectMapperType"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RedirectSpecificationImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "io.restassured.internal.RedirectSpecificationImpl",
      "org.assertj.core.internal.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "io.restassured.internal.RestAssuredResponseOptionsImpl",
      "io.restassured.internal.RestAssuredResponseImpl",
      "io.restassured.internal.RestAssuredResponseOptionsGroovyImpl",
      "com.fasterxml.jackson.core.util.BufferRecycler",
      "com.fasterxml.jackson.core.util.ByteArrayBuilder",
      "io.restassured.authentication.PreemptiveOAuth2HeaderScheme",
      "io.restassured.internal.ResponseSpecificationImpl",
      "io.restassured.internal.assertion.BodyMatcherGroup",
      "io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure",
      "org.apache.commons.lang3.Validate",
      "io.restassured.authentication.OAuthScheme",
      "io.restassured.config.RestAssuredConfig",
      "io.restassured.config.RedirectConfig",
      "io.restassured.config.HttpClientConfig",
      "io.restassured.config.HttpClientConfig$2",
      "io.restassured.config.HttpClientConfig$1",
      "org.apache.http.entity.mime.HttpMultipartMode",
      "io.restassured.config.LogConfig",
      "io.restassured.config.EncoderConfig$1",
      "io.restassured.config.EncoderConfig",
      "org.apache.commons.lang3.StringUtils",
      "io.restassured.config.DecoderConfig$1",
      "io.restassured.http.ContentType",
      "io.restassured.config.DecoderConfig",
      "io.restassured.config.SessionConfig",
      "io.restassured.config.ObjectMapperConfig",
      "io.restassured.path.json.mapper.factory.DefaultGsonObjectMapperFactory",
      "io.restassured.path.json.mapper.factory.DefaultJackson1ObjectMapperFactory",
      "io.restassured.path.json.mapper.factory.DefaultJackson2ObjectMapperFactory",
      "io.restassured.internal.common.classpath.ClassPathResolver",
      "io.restassured.common.mapper.resolver.ObjectMapperResolver",
      "io.restassured.path.xml.mapper.factory.DefaultJAXBObjectMapperFactory",
      "io.restassured.path.json.mapper.factory.DefaultJohnzonObjectMapperFactory",
      "io.restassured.path.json.mapper.factory.DefaultYassonObjectMapperFactory",
      "io.restassured.path.xml.mapper.factory.DefaultJakartaEEObjectMapperFactory",
      "io.restassured.config.ConnectionConfig",
      "io.restassured.config.JsonConfig",
      "io.restassured.path.json.config.JsonPathConfig$NumberReturnType",
      "io.restassured.config.XmlConfig",
      "io.restassured.config.SSLConfig",
      "org.apache.http.conn.ssl.AbstractVerifier",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.apache.http.conn.ssl.AllowAllHostnameVerifier",
      "org.apache.http.conn.ssl.BrowserCompatHostnameVerifier",
      "org.apache.http.conn.ssl.StrictHostnameVerifier",
      "org.apache.http.conn.ssl.SSLSocketFactory",
      "io.restassured.internal.common.assertion.AssertParameter",
      "io.restassured.config.MatcherConfig",
      "io.restassured.config.HeaderConfig",
      "io.restassured.config.HeaderConfig$1",
      "io.restassured.config.MultiPartConfig",
      "io.restassured.config.ParamConfig",
      "io.restassured.config.OAuthConfig",
      "io.restassured.internal.LogRequestAndResponseOnFailListener",
      "io.restassured.config.FailureConfig",
      "io.restassured.config.CsrfConfig",
      "io.restassured.internal.log.LogRepository",
      "io.restassured.specification.ProxySpecification",
      "io.restassured.authentication.CertAuthScheme",
      "io.restassured.internal.RequestSpecificationImpl",
      "io.restassured.authentication.NoAuthScheme",
      "io.restassured.http.Headers",
      "io.restassured.internal.MultiValueEntity",
      "io.restassured.http.Cookies",
      "io.restassured.internal.RequestSpecificationImpl$1",
      "io.restassured.internal.support.ParameterUpdater",
      "io.restassured.internal.RequestSpecificationImpl$_removeCookie_closure2",
      "io.restassured.authentication.FormAuthScheme",
      "io.restassured.internal.http.HTTPBuilder",
      "io.restassured.authentication.ExplicitNoAuthScheme",
      "io.restassured.internal.ResponseParserRegistrar",
      "io.restassured.internal.ResponseParserRegistrar$1",
      "io.restassured.RestAssured",
      "groovyjarjarasm.asm.ClassVisitor",
      "groovyjarjarasm.asm.ClassWriter",
      "groovyjarjarasm.asm.SymbolTable",
      "groovyjarjarasm.asm.ByteVector",
      "groovyjarjarasm.asm.MethodVisitor",
      "groovyjarjarasm.asm.MethodWriter",
      "groovyjarjarasm.asm.Symbol",
      "groovyjarjarasm.asm.SymbolTable$Entry",
      "groovyjarjarasm.asm.commons.AnalyzerAdapter",
      "groovyjarjarasm.asm.Type",
      "io.restassured.authentication.OAuth2Scheme",
      "io.restassured.authentication.PreemptiveBasicAuthScheme",
      "io.restassured.internal.SpecificationMerger",
      "io.restassured.internal.http.ContentTypeExtractor",
      "groovyjarjarasm.asm.tree.MethodNode",
      "io.restassured.authentication.BasicAuthScheme",
      "io.restassured.authentication.NTLMAuthScheme",
      "org.glassfish.jaxb.core.unmarshaller.DOMScanner",
      "org.glassfish.jaxb.core.v2.runtime.unmarshaller.LocatorEx$Snapshot",
      "jakarta.xml.bind.helpers.ValidationEventLocatorImpl",
      "jakarta.xml.bind.helpers.Messages",
      "io.restassured.filter.log.RequestLoggingFilter",
      "groovyjarjarasm.asm.commons.Method",
      "groovyjarjarasm.asm.tree.AbstractInsnNode",
      "groovyjarjarasm.asm.tree.FrameNode",
      "io.restassured.internal.print.ResponsePrinter",
      "io.restassured.internal.support.Prettifier",
      "io.restassured.internal.http.CharsetExtractor",
      "io.restassured.internal.http.ContentTypeSubTypeExtractor",
      "io.restassured.internal.ValidatableResponseOptionsImpl",
      "io.restassured.internal.ValidatableResponseImpl",
      "io.restassured.filter.log.StatusCodeBasedLoggingFilter",
      "io.restassured.filter.log.ResponseLoggingFilter",
      "org.hamcrest.Matchers",
      "org.hamcrest.BaseMatcher",
      "org.hamcrest.DiagnosingMatcher",
      "org.hamcrest.core.IsInstanceOf",
      "com.fasterxml.jackson.core.type.ResolvedType",
      "com.fasterxml.jackson.databind.JavaType",
      "com.fasterxml.jackson.databind.type.TypeBindings",
      "com.fasterxml.jackson.databind.type.TypeBase",
      "com.fasterxml.jackson.databind.type.ResolvedRecursiveType",
      "com.fasterxml.jackson.databind.JsonDeserializer",
      "com.fasterxml.jackson.databind.DeserializationFeature",
      "com.fasterxml.jackson.databind.deser.std.StdDeserializer",
      "com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer",
      "com.fasterxml.jackson.databind.deser.std.FromStringDeserializer",
      "com.fasterxml.jackson.databind.ext.DOMDeserializer",
      "com.fasterxml.jackson.databind.ext.DOMDeserializer$DocumentDeserializer",
      "io.restassured.config.ConnectionConfig$CloseIdleConnectionConfig",
      "io.restassured.config.DecoderConfig$ContentDecoder",
      "io.restassured.config.MatcherConfig$ErrorDescriptionType",
      "io.restassured.config.ParamConfig$UpdateStrategy"
    );
  }
}
