# Compile 34 generated test classes for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
( mkdir -p 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre' && cd 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/google/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/testers/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/testing/*_ESTest*.java
)
# Compile 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
( mkdir -p 'compile/obfs/commons-io/commons-io/2.15.0' && cd 'compile/obfs/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/comparator/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/filefilter/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/monitor/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/output/*_ESTest*.java
)
# Compile 2 generated test classes for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for obfs
( mkdir -p 'compile/obfs/commons-logging/commons-logging/1.3.0' && cd 'compile/obfs/commons-logging/commons-logging/1.3.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-logging/commons-logging/1.3.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-logging/commons-logging/1.3.0/evosuite-tests/org/apache/commons/logging/impl/*_ESTest*.java
)
# Compile 2 generated test classes for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for obfs
( mkdir -p 'compile/obfs/commons-net/commons-net/3.10.0' && cd 'compile/obfs/commons-net/commons-net/3.10.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/commons-net-3.10.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/commons-net-3.10.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-net/commons-net/3.10.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-net/commons-net/3.10.0/evosuite-tests/org/apache/commons/net/ftp/*_ESTest*.java
)
# Compile 2 generated test classes for io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar for obfs
( mkdir -p 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && cd 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/micronaut-kubernetes-discovery-client-3.4.1-oracle-00001.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/micronaut-kubernetes-discovery-client-3.4.1-oracle-00001.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests/io/micronaut/kubernetes/util/*_ESTest*.java
)
# Compile 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for obfs
( mkdir -p 'compile/obfs/junit/junit/4.13.2' && cd 'compile/obfs/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/junit/junit/4.13.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/junit/junit/4.13.2/evosuite-tests/junit/runner/*_ESTest*.java
)
