#!/bin/bash
set -v
# Compile 22 generated test classes for com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.0' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/driver/windows/registry/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/hardware/platform/unix/freebsd/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/hardware/platform/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/jna/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/jna/platform/unix/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/software/os/linux/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/software/os/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/util/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.0/evosuite-tests/oshi/util/platform/windows/*_ESTest*.java
)
# Compile 22 generated test classes for com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.1' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/driver/windows/registry/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/hardware/platform/unix/freebsd/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/hardware/platform/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/jna/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/jna/platform/unix/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/software/os/linux/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/software/os/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/util/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.1/evosuite-tests/oshi/util/platform/windows/*_ESTest*.java
)
# Compile 30 generated test classes for com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.2' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/driver/windows/registry/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/hardware/platform/unix/freebsd/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/hardware/platform/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/jna/platform/linux/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/jna/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/jna/platform/unix/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/jna/platform/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/software/os/linux/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/software/os/windows/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/util/platform/mac/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/oshi/oshi-core/6.4.2/evosuite-tests/oshi/util/platform/windows/*_ESTest*.java
)
# Compile 2 generated test classes for com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/zafarkhaja/java-semver/0.9.0' && cd 'compile/mvnc/com/github/zafarkhaja/java-semver/0.9.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/github/zafarkhaja/java-semver/0.9.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/github/zafarkhaja/java-semver/0.9.0/evosuite-tests/com/github/zafarkhaja/semver/*_ESTest*.java
)
# Compile 14 generated test classes for com/google/auto/auto-common/1.2.1/auto-common-1.2.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/auto/auto-common/1.2.1' && cd 'compile/mvnc/com/google/auto/auto-common/1.2.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/auto/auto-common/1.2.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/auto/auto-common/1.2.1/evosuite-tests/com/google/auto/common/*_ESTest*.java
)
# Compile 6 generated test classes for com/google/auto/auto-common/1.2.2/auto-common-1.2.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/auto/auto-common/1.2.2' && cd 'compile/mvnc/com/google/auto/auto-common/1.2.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/auto/auto-common/1.2.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/auto/auto-common/1.2.2/evosuite-tests/com/google/auto/common/*_ESTest*.java
)
# Compile 34 generated test classes for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && cd 'compile/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/google/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/collect/testing/testers/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava-testlib/32.1.2-jre/evosuite-tests/com/google/common/testing/*_ESTest*.java
)
# Compile 320 generated test classes for com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/guava/guava/31.0.1-jre' && cd 'compile/mvnc/com/google/guava/guava/31.0.1-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/base/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/cache/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/collect/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/escape/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/eventbus/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/graph/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/hash/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/io/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/math/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/net/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/primitives/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/reflect/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/common/util/concurrent/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/guava/guava/31.0.1-jre/evosuite-tests/com/google/thirdparty/publicsuffix/*_ESTest*.java
)
# Compile 2 generated test classes for com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0/evosuite-tests/com/google/inject/assistedinject/*_ESTest*.java
)
# Compile 2 generated test classes for com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0/evosuite-tests/com/google/inject/assistedinject/*_ESTest*.java
)
# Compile 6 generated test classes for com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-servlet/6.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-servlet/6.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/inject/extensions/guice-servlet/6.0.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/inject/extensions/guice-servlet/6.0.0/evosuite-tests/com/google/inject/servlet/*_ESTest*.java
)
# Compile 6 generated test classes for com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-servlet/7.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-servlet/7.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/inject/extensions/guice-servlet/7.0.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/inject/extensions/guice-servlet/7.0.0/evosuite-tests/com/google/inject/servlet/*_ESTest*.java
)
# Compile 44 generated test classes for com/google/jimfs/jimfs/1.2/jimfs-1.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/jimfs/jimfs/1.2' && cd 'compile/mvnc/com/google/jimfs/jimfs/1.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/jimfs-1.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/jimfs-1.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/jimfs/jimfs/1.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/jimfs/jimfs/1.2/evosuite-tests/com/google/common/jimfs/*_ESTest*.java
)
# Compile 2 generated test classes for com/google/zxing/core/3.5.0/core-3.5.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.0' && cd 'compile/mvnc/com/google/zxing/core/3.5.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/core-3.5.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/core-3.5.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/zxing/core/3.5.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/zxing/core/3.5.0/evosuite-tests/com/google/zxing/oned/*_ESTest*.java
)
# Compile 2 generated test classes for com/google/zxing/core/3.5.1/core-3.5.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.1' && cd 'compile/mvnc/com/google/zxing/core/3.5.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/core-3.5.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/core-3.5.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/zxing/core/3.5.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/zxing/core/3.5.1/evosuite-tests/com/google/zxing/oned/*_ESTest*.java
)
# Compile 2 generated test classes for com/google/zxing/core/3.5.3/core-3.5.3.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.3' && cd 'compile/mvnc/com/google/zxing/core/3.5.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/core-3.5.3.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/core-3.5.3.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/zxing/core/3.5.3/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/google/zxing/core/3.5.3/evosuite-tests/com/google/zxing/oned/*_ESTest*.java
)
# Compile 2 generated test classes for com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.jar for mvnc
( mkdir -p 'compile/mvnc/com/squareup/okhttp/okhttp/2.7.5' && cd 'compile/mvnc/com/squareup/okhttp/okhttp/2.7.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/squareup/okhttp/okhttp/2.7.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/com/squareup/okhttp/okhttp/2.7.5/evosuite-tests/com/squareup/okhttp/internal/framed/*_ESTest*.java
)
# Compile 2 generated test classes for commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar for mvnc
( mkdir -p 'compile/mvnc/commons-configuration/commons-configuration/1.10' && cd 'compile/mvnc/commons-configuration/commons-configuration/1.10' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-configuration/commons-configuration/1.10/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-configuration/commons-configuration/1.10/evosuite-tests/org/apache/commons/configuration/*_ESTest*.java
)
# Compile 2 generated test classes for commons-io/commons-io/2.14.0/commons-io-2.14.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.14.0' && cd 'compile/mvnc/commons-io/commons-io/2.14.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.14.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.14.0/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java
)
# Compile 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.0' && cd 'compile/mvnc/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/comparator/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/filefilter/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/monitor/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/output/*_ESTest*.java
)
# Compile 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.0' && cd 'compile/mvnc/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/comparator/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/filefilter/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/monitor/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.0/evosuite-tests/org/apache/commons/io/output/*_ESTest*.java
)
# Compile 2 generated test classes for commons-io/commons-io/2.15.1/commons-io-2.15.1.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.1' && cd 'compile/mvnc/commons-io/commons-io/2.15.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.15.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.15.1/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java
)
# Compile 2 generated test classes for commons-io/commons-io/2.16.0/commons-io-2.16.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.16.0' && cd 'compile/mvnc/commons-io/commons-io/2.16.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/commons-io-2.16.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/commons-io-2.16.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-io/commons-io/2.16.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-io/commons-io/2.16.0/evosuite-tests/org/apache/commons/io/input/*_ESTest*.java
)
# Compile 2 generated test classes for commons-logging/commons-logging/1.2/commons-logging-1.2.jar for mvnc
( mkdir -p 'compile/mvnc/commons-logging/commons-logging/1.2' && cd 'compile/mvnc/commons-logging/commons-logging/1.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-logging/commons-logging/1.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-logging/commons-logging/1.2/evosuite-tests/org/apache/commons/logging/impl/*_ESTest*.java
)
# Compile 2 generated test classes for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-logging/commons-logging/1.3.0' && cd 'compile/mvnc/commons-logging/commons-logging/1.3.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-logging/commons-logging/1.3.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-logging/commons-logging/1.3.0/evosuite-tests/org/apache/commons/logging/impl/*_ESTest*.java
)
# Compile 2 generated test classes for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-net/commons-net/3.10.0' && cd 'compile/mvnc/commons-net/commons-net/3.10.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/commons-net-3.10.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/commons-net-3.10.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/commons-net/commons-net/3.10.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/commons-net/commons-net/3.10.0/evosuite-tests/org/apache/commons/net/ftp/*_ESTest*.java
)
# Compile 2 generated test classes for io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar for mvnc
( mkdir -p 'compile/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && cd 'compile/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests/io/micronaut/kubernetes/util/*_ESTest*.java
)
# Compile 2 generated test classes for io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-buffer/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-buffer/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/netty/netty-buffer/4.1.102.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/netty/netty-buffer/4.1.102.Final/evosuite-tests/io/netty/buffer/*_ESTest*.java
)
# Compile 6 generated test classes for io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-codec-http/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-codec-http/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final/evosuite-tests/io/netty/handler/codec/http/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final/evosuite-tests/io/netty/handler/codec/http/multipart/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/netty/netty-codec-http/4.1.102.Final/evosuite-tests/io/netty/handler/codec/spdy/*_ESTest*.java
)
# Compile 4 generated test classes for io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-codec/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-codec/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/netty/netty-codec/4.1.102.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/io/netty/netty-codec/4.1.102.Final/evosuite-tests/io/netty/handler/codec/compression/*_ESTest*.java
)
# Compile 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for mvnc
( mkdir -p 'compile/mvnc/junit/junit/4.13.2' && cd 'compile/mvnc/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/junit/junit/4.13.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/junit/junit/4.13.2/evosuite-tests/junit/runner/*_ESTest*.java
)
# Compile 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for mvnc
( mkdir -p 'compile/mvnc/junit/junit/4.13.2' && cd 'compile/mvnc/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/junit/junit/4.13.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/junit/junit/4.13.2/evosuite-tests/junit/runner/*_ESTest*.java
)
# Compile 4 generated test classes for org/apache/avro/avro/1.11.1/avro-1.11.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/avro/avro/1.11.1' && cd 'compile/mvnc/org/apache/avro/avro/1.11.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/avro-1.11.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/avro-1.11.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/avro/avro/1.11.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/avro/avro/1.11.1/evosuite-tests/org/apache/avro/file/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/commons/commons-configuration2/2.7' && cd 'compile/mvnc/org/apache/commons/commons-configuration2/2.7' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/commons/commons-configuration2/2.7/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/commons/commons-configuration2/2.7/evosuite-tests/org/apache/commons/configuration2/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/commons/commons-configuration2/2.8.0' && cd 'compile/mvnc/org/apache/commons/commons-configuration2/2.8.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/commons/commons-configuration2/2.8.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/commons/commons-configuration2/2.8.0/evosuite-tests/org/apache/commons/configuration2/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/curator/curator-recipes/5.6.0' && cd 'compile/mvnc/org/apache/curator/curator-recipes/5.6.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/curator/curator-recipes/5.6.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/curator/curator-recipes/5.6.0/evosuite-tests/org/apache/curator/framework/recipes/locks/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8' && cd 'compile/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8/evosuite-tests/org/apache/cxf/transport/http/*_ESTest*.java
)
# Compile 10 generated test classes for org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5' && cd 'compile/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/evosuite-tests/org/apache/hadoop/mapred/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/evosuite-tests/org/apache/hadoop/mapreduce/jobhistory/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/evosuite-tests/org/apache/hadoop/mapreduce/lib/chain/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4' && cd 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4/evosuite-tests/org/apache/hc/core5/reactor/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5' && cd 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5/evosuite-tests/org/apache/hc/core5/reactor/*_ESTest*.java
)
# Compile 2 generated test classes for org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/logging/log4j/log4j-api/2.17.1' && cd 'compile/mvnc/org/apache/logging/log4j/log4j-api/2.17.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/logging/log4j/log4j-api/2.17.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/apache/logging/log4j/log4j-api/2.17.1/evosuite-tests/org/apache/logging/log4j/spi/*_ESTest*.java
)
# Compile 2 generated test classes for org/codehaus/janino/janino/3.1.12/janino-3.1.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/codehaus/janino/janino/3.1.12' && cd 'compile/mvnc/org/codehaus/janino/janino/3.1.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/janino-3.1.12.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/janino-3.1.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/codehaus/janino/janino/3.1.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/codehaus/janino/janino/3.1.12/evosuite-tests/org/codehaus/janino/*_ESTest*.java
)
# Compile 2 generated test classes for org/codehaus/janino/janino/3.1.9/janino-3.1.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/codehaus/janino/janino/3.1.9' && cd 'compile/mvnc/org/codehaus/janino/janino/3.1.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/janino-3.1.9.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/janino-3.1.9.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/codehaus/janino/janino/3.1.9/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/codehaus/janino/janino/3.1.9/evosuite-tests/org/codehaus/janino/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.15.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.15.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.15.0/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.15.0/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.16.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.16.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.16.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.16.1/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.16.1/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.16.2' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.16.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.16.2/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.16.2/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.16.2/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.17.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.17.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.17.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.17.0/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.17.0/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.18.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.18.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.18.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.18.0/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.18.0/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.19.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.0/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.0/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.19.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.1/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.1/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.3' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.19.3/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.3/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.3/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.4' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.19.4/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.4/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.19.4/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.20.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.20.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.20.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.20.0/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.20.0/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.20.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.20.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.20.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.20.1/evosuite-tests/org/flywaydb/core/api/configuration/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.20.1/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 2 generated test classes for org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.21.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.21.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/flywaydb/flyway-core/9.21.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/flywaydb/flyway-core/9.21.1/evosuite-tests/org/flywaydb/core/internal/configuration/*_ESTest*.java
)
# Compile 4 generated test classes for org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/jfree/jfreechart/1.5.4' && cd 'compile/mvnc/org/jfree/jfreechart/1.5.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/jfree/jfreechart/1.5.4/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/jfree/jfreechart/1.5.4/evosuite-tests/org/jfree/chart/plot/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/jfree/jfreechart/1.5.4/evosuite-tests/org/jfree/chart/util/*_ESTest*.java
)
# Compile 4 generated test classes for org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.5' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/threeten/threetenbp/1.6.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.5/evosuite-tests/org/threeten/bp/chrono/*_ESTest*.java
)
# Compile 6 generated test classes for org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.6' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.6' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/threeten/threetenbp/1.6.6/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.6/evosuite-tests/org/threeten/bp/chrono/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.6/evosuite-tests/org/threeten/bp/temporal/*_ESTest*.java
)
# Compile 6 generated test classes for org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.7' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.7' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/threeten/threetenbp/1.6.7/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.7/evosuite-tests/org/threeten/bp/chrono/*_ESTest*.java /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.7/evosuite-tests/org/threeten/bp/temporal/*_ESTest*.java
)
# Compile 2 generated test classes for org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.8' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.8' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/threeten/threetenbp/1.6.8/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.8/evosuite-tests/org/threeten/bp/chrono/*_ESTest*.java
)
# Compile 4 generated test classes for org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.9' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.pom dependency:copy-dependencies && ln -s /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/threeten/threetenbp/1.6.9/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation/find-diff-classes/testgen/mvnc/org/threeten/threetenbp/1.6.9/evosuite-tests/org/threeten/bp/chrono/*_ESTest*.java
)
