#!/bin/bash
set -v
echo "Will write test results under RUNDIR=${RUNDIR:=run}"   # Default to 'run' if not overridden
# No compiled classes found for compile/obfs/ch/qos/logback/logback-access/1.3.11 so won't create ${RUNDIR}/obfs/ch/qos/logback/logback-access/1.3.11.
# No compiled classes found for compile/obfs/ch/qos/logback/logback-core/1.3.11 so won't create ${RUNDIR}/obfs/ch/qos/logback/logback-core/1.3.11.
( mkdir -p "${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre" && cd 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre'
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/testing/AbstractPackageSanityTests_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.testing.AbstractPackageSanityTests_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.AbstractPackageSanityTests_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.AbstractPackageSanityTests_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/testing/ClassSanityTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.testing.ClassSanityTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.ClassSanityTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.ClassSanityTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/Helpers_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.Helpers_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.Helpers_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.Helpers_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/NavigableSetTestSuiteBuilder_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/testers/SortedMapNavigationTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/testers/CollectionRetainAllTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/SpliteratorTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.SpliteratorTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.SpliteratorTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.SpliteratorTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForQueuesInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForSetsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/AbstractIteratorTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.AbstractIteratorTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.AbstractIteratorTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.AbstractIteratorTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/MultimapPutIterableTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/MapGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.google.MapGenerators_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MapGenerators_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MapGenerators_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/SortedMapGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.google.SortedMapGenerators_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMapGenerators_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMapGenerators_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/SortedMultisetTestSuiteBuilder_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForListsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForMapsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest.err"
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/DerivedCollectionGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "com.google.common.collect.testing.DerivedCollectionGenerators_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.DerivedCollectionGenerators_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.DerivedCollectionGenerators_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/commons-io/commons-io/2.15.0" && cd 'compile/obfs/commons-io/commons-io/2.15.0'
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/filefilter/NotFileFilter_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.io.filefilter.NotFileFilter_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.filefilter.NotFileFilter_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.filefilter.NotFileFilter_ESTest.err"
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/input/Tailer_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.io.input.Tailer_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.input.Tailer_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.input.Tailer_ESTest.err"
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/output/UncheckedAppendableImpl_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.io.output.UncheckedAppendableImpl_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.output.UncheckedAppendableImpl_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.output.UncheckedAppendableImpl_ESTest.err"
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/comparator/ReverseFileComparator_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.io.comparator.ReverseFileComparator_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.comparator.ReverseFileComparator_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.comparator.ReverseFileComparator_ESTest.err"
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/monitor/FileAlterationObserver_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.io.monitor.FileAlterationObserver_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.monitor.FileAlterationObserver_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.monitor.FileAlterationObserver_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/commons-logging/commons-logging/1.3.0" && cd 'compile/obfs/commons-logging/commons-logging/1.3.0'
# Run compiled test class compile/obfs/commons-logging/commons-logging/1.3.0/org/apache/commons/logging/impl/Slf4jLogFactory_ESTest.class for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.logging.impl.Slf4jLogFactory_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-logging/commons-logging/1.3.0/org.apache.commons.logging.impl.Slf4jLogFactory_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-logging/commons-logging/1.3.0/org.apache.commons.logging.impl.Slf4jLogFactory_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/commons-net/commons-net/3.10.0" && cd 'compile/obfs/commons-net/commons-net/3.10.0'
# Run compiled test class compile/obfs/commons-net/commons-net/3.10.0/org/apache/commons/net/ftp/FTPFile_ESTest.class for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/commons-net-3.10.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.apache.commons.net.ftp.FTPFile_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-net/commons-net/3.10.0/org.apache.commons.net.ftp.FTPFile_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/commons-net/commons-net/3.10.0/org.apache.commons.net.ftp.FTPFile_ESTest.err"
)
# No compiled classes found for compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1 so won't create ${RUNDIR}/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5 so won't create ${RUNDIR}/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5.
( mkdir -p "${RUNDIR}/obfs/junit/junit/4.13.2" && cd 'compile/obfs/junit/junit/4.13.2'
# Run compiled test class compile/obfs/junit/junit/4.13.2/junit/runner/BaseTestRunner_ESTest.class for junit/junit/4.13.2/junit-4.13.2.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "junit.runner.BaseTestRunner_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/junit/junit/4.13.2/junit.runner.BaseTestRunner_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/junit/junit/4.13.2/junit.runner.BaseTestRunner_ESTest.err"
)
# No compiled classes found for compile/obfs/org/apache/commons/commons-text/1.11.0 so won't create ${RUNDIR}/obfs/org/apache/commons/commons-text/1.11.0.
# No compiled classes found for compile/obfs/org/apache/zookeeper/zookeeper/3.9.1 so won't create ${RUNDIR}/obfs/org/apache/zookeeper/zookeeper/3.9.1.
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org/glassfish/jersey/netty/connector/LocalizationMessages_ESTest.class for org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org/glassfish/jersey/grizzly2/httpserver/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org/glassfish/jersey/jdkhttp/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org/glassfish/jersey/servlet/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org/glassfish/jersey/servlet/init/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org/glassfish/jersey/simple/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org/glassfish/jersey/client/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.client.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org.glassfish.jersey.client.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org.glassfish.jersey.client.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org/glassfish/jersey/server/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.server.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org.glassfish.jersey.server.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org.glassfish.jersey.server.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org/glassfish/jersey/inject/hk2/LocalizationMessages_ESTest.class for org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org/glassfish/jersey/jaxb/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  org.junit.runner.JUnitCore "org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest.err"
)
# No compiled classes found for compile/obfs/org/glassfish/jersey/media/jersey-media-sse/3.0.12 so won't create ${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-sse/3.0.12.
# No compiled classes found for compile/obfs/org/slf4j/slf4j-simple/2.0.9 so won't create ${RUNDIR}/obfs/org/slf4j/slf4j-simple/2.0.9.
