#!/bin/bash
set -v
# No compiled classes found for compile/obfs/ch/qos/logback/logback-access/1.3.11 so won't create run/obfs/ch/qos/logback/logback-access/1.3.11.
# No compiled classes found for compile/obfs/ch/qos/logback/logback-core/1.3.11 so won't create run/obfs/ch/qos/logback/logback-core/1.3.11.
( mkdir -p 'run/obfs/com/google/guava/guava-testlib/32.1.2-jre' && cd 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre'
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/testing/AbstractPackageSanityTests_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.testing.AbstractPackageSanityTests_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.AbstractPackageSanityTests_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.AbstractPackageSanityTests_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/testing/ClassSanityTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.testing.ClassSanityTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.ClassSanityTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.testing.ClassSanityTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/Helpers_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.Helpers_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.Helpers_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.Helpers_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/NavigableSetTestSuiteBuilder_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.NavigableSetTestSuiteBuilder_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/testers/SortedMapNavigationTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.SortedMapNavigationTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/testers/CollectionRetainAllTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.testers.CollectionRetainAllTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/SpliteratorTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.SpliteratorTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.SpliteratorTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.SpliteratorTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForQueuesInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForQueuesInJavaUtil_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForSetsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForSetsInJavaUtil_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/AbstractIteratorTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.AbstractIteratorTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.AbstractIteratorTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.AbstractIteratorTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/MultimapPutIterableTester_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MultimapPutIterableTester_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/MapGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.google.MapGenerators_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MapGenerators_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.MapGenerators_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/SortedMapGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.google.SortedMapGenerators_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMapGenerators_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMapGenerators_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/google/SortedMultisetTestSuiteBuilder_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.google.SortedMultisetTestSuiteBuilder_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForListsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForListsInJavaUtil_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/TestsForMapsInJavaUtil_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.TestsForMapsInJavaUtil_ESTest.err
# Run compiled test class compile/obfs/com/google/guava/guava-testlib/32.1.2-jre/com/google/common/collect/testing/DerivedCollectionGenerators_ESTest.class for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore com.google.common.collect.testing.DerivedCollectionGenerators_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.DerivedCollectionGenerators_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/com/google/guava/guava-testlib/32.1.2-jre/com.google.common.collect.testing.DerivedCollectionGenerators_ESTest.err
)
( mkdir -p 'run/obfs/commons-io/commons-io/2.15.0' && cd 'compile/obfs/commons-io/commons-io/2.15.0'
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/filefilter/NotFileFilter_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.io.filefilter.NotFileFilter_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.filefilter.NotFileFilter_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.filefilter.NotFileFilter_ESTest.err
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/input/Tailer_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.io.input.Tailer_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.input.Tailer_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.input.Tailer_ESTest.err
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/output/UncheckedAppendableImpl_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.io.output.UncheckedAppendableImpl_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.output.UncheckedAppendableImpl_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.output.UncheckedAppendableImpl_ESTest.err
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/comparator/ReverseFileComparator_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.io.comparator.ReverseFileComparator_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.comparator.ReverseFileComparator_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.comparator.ReverseFileComparator_ESTest.err
# Run compiled test class compile/obfs/commons-io/commons-io/2.15.0/org/apache/commons/io/monitor/FileAlterationObserver_ESTest.class for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.io.monitor.FileAlterationObserver_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.monitor.FileAlterationObserver_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-io/commons-io/2.15.0/org.apache.commons.io.monitor.FileAlterationObserver_ESTest.err
)
( mkdir -p 'run/obfs/commons-logging/commons-logging/1.3.0' && cd 'compile/obfs/commons-logging/commons-logging/1.3.0'
# Run compiled test class compile/obfs/commons-logging/commons-logging/1.3.0/org/apache/commons/logging/impl/Slf4jLogFactory_ESTest.class for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.logging.impl.Slf4jLogFactory_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-logging/commons-logging/1.3.0/org.apache.commons.logging.impl.Slf4jLogFactory_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-logging/commons-logging/1.3.0/org.apache.commons.logging.impl.Slf4jLogFactory_ESTest.err
)
( mkdir -p 'run/obfs/commons-net/commons-net/3.10.0' && cd 'compile/obfs/commons-net/commons-net/3.10.0'
# Run compiled test class compile/obfs/commons-net/commons-net/3.10.0/org/apache/commons/net/ftp/FTPFile_ESTest.class for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/commons-net-3.10.0.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore org.apache.commons.net.ftp.FTPFile_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-net/commons-net/3.10.0/org.apache.commons.net.ftp.FTPFile_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/commons-net/commons-net/3.10.0/org.apache.commons.net.ftp.FTPFile_ESTest.err
)
# No compiled classes found for compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1 so won't create run/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2 so won't create run/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5 so won't create run/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5.
( mkdir -p 'run/obfs/junit/junit/4.13.2' && cd 'compile/obfs/junit/junit/4.13.2'
# Run compiled test class compile/obfs/junit/junit/4.13.2/junit/runner/BaseTestRunner_ESTest.class for junit/junit/4.13.2/junit-4.13.2.jar for obfs
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/junit-4.13.2.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore junit.runner.BaseTestRunner_ESTest > /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/junit/junit/4.13.2/junit.runner.BaseTestRunner_ESTest.out 2> /home/wtwhite/code/regression-test-generation/find-diff-classes/run/obfs/junit/junit/4.13.2/junit.runner.BaseTestRunner_ESTest.err
)
# No compiled classes found for compile/obfs/org/slf4j/slf4j-simple/2.0.9 so won't create run/obfs/org/slf4j/slf4j-simple/2.0.9.
