#!/bin/bash
set -v
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/ch/qos/logback/logback-access/1.3.11/logback-access-1.3.11.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.3.11/logback-core-1.3.11.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.4.1/jackson-databind-2.13.4.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.4.2/jackson-databind-2.13.4.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/javaparser/javaparser-core/3.24.4/javaparser-core-3.24.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/jimfs-1.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.25.1/protobuf-java-3.25.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.3/truth-1.1.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.5/truth-1.1.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.2.0/truth-1.2.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/core-3.5.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/core-3.5.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/core-3.5.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/commons-io-2.16.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/commons-net-3.10.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.3.RELEASE/lettuce-core-6.2.3.RELEASE.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.4.RELEASE/lettuce-core-6.2.4.RELEASE.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/lettuce/lettuce-core/6.2.5.RELEASE/lettuce-core-6.2.5.RELEASE.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2/micronaut-oraclecloud-bmc-budget-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2/micronaut-oraclecloud-bmc-containerengine-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2/micronaut-oraclecloud-bmc-core-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2/micronaut-oraclecloud-bmc-fusionapps-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2/micronaut-oraclecloud-bmc-identitydomains-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2/micronaut-oraclecloud-bmc-loganalytics-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2/micronaut-oraclecloud-bmc-opsi-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2/micronaut-oraclecloud-bmc-tenantmanagercontrolplane-3.0.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/starter/micronaut-starter-api/3.8.5/micronaut-starter-api-3.8.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-dns/4.1.102.Final/netty-codec-dns-4.1.102.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/antlr/ST4/4.3.3/ST4-4.3.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/avro-1.11.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.6.2/cxf-rt-transports-http-3.6.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.0/maven-core-3.9.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.1/maven-core-3.9.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.2/maven-core-3.9.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.3/maven-core-3.9.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.4/maven-core-3.9.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.5/maven-core-3.9.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-core/3.9.6/maven-core-3.9.6.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.0/maven-plugin-api-3.9.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.1/maven-plugin-api-3.9.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.2/maven-plugin-api-3.9.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.3/maven-plugin-api-3.9.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.4/maven-plugin-api-3.9.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.6/maven-plugin-api-3.9.6.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.9.7/maven-plugin-api-3.9.7.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.9.1/zookeeper-3.9.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/groovy/groovy/2.5.23/groovy-2.5.23.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/janino-3.1.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/janino-3.1.9.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.22.0/flyway-core-9.22.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.22.1/flyway-core-9.22.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.22.2/flyway-core-9.22.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.22.3/flyway-core-9.22.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-sse/3.0.12/jersey-media-sse-3.0.12.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/javassist/javassist/3.30.0-GA/javassist-3.30.0-GA.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/javassist/javassist/3.30.1-GA/javassist-3.30.1-GA.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jgrapht/jgrapht-core/1.5.1/jgrapht-core-1.5.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jgrapht/jgrapht-core/1.5.2/jgrapht-core-1.5.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.24.3/redisson-3.24.3.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.25.0/redisson-3.25.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.25.1/redisson-3.25.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.25.2/redisson-3.25.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.26.0/redisson-3.26.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.26.1/redisson-3.26.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.27.0/redisson-3.27.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.27.1/redisson-3.27.1.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.27.2/redisson-3.27.2.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.29.0/redisson-3.29.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/redisson/redisson/3.30.0/redisson-3.30.0.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/slf4j/slf4j-simple/2.0.9/slf4j-simple-2.0.9.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-commons/3.1.7/spring-cloud-commons-3.1.7.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.pom dependency:copy-dependencies >&2
mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.pom dependency:copy-dependencies >&2
