#!/bin/bash
set -v
# Set up deps for 34 generated test classes for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for obfs
( mkdir -p 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre' && cd 'compile/obfs/com/google/guava/guava-testlib/32.1.2-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/com/google/guava/guava-testlib/32.1.2-jre/target t || true ) )
# Set up deps for 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for obfs
( mkdir -p 'compile/obfs/commons-io/commons-io/2.15.0' && cd 'compile/obfs/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-io/commons-io/2.15.0/target t || true ) )
# Set up deps for 2 generated test classes for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for obfs
( mkdir -p 'compile/obfs/commons-logging/commons-logging/1.3.0' && cd 'compile/obfs/commons-logging/commons-logging/1.3.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-logging/commons-logging/1.3.0/target t || true ) )
# Set up deps for 2 generated test classes for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for obfs
( mkdir -p 'compile/obfs/commons-net/commons-net/3.10.0' && cd 'compile/obfs/commons-net/commons-net/3.10.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/commons-net-3.10.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/commons-net/commons-net/3.10.0/target t || true ) )
# Set up deps for 2 generated test classes for io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar for obfs
( mkdir -p 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && cd 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/micronaut-kubernetes-discovery-client-3.4.1-oracle-00001.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/target t || true ) )
# Set up deps for 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for obfs
( mkdir -p 'compile/obfs/junit/junit/4.13.2' && cd 'compile/obfs/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/junit/junit/4.13.2/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/target t || true ) )
