#!/bin/bash
set -v
# Set up deps for 22 generated test classes for com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.0' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/oshi-core-6.4.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.0/target t || true ) )
# Set up deps for 22 generated test classes for com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.1' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/oshi-core-6.4.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.1/target t || true ) )
# Set up deps for 30 generated test classes for com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/oshi/oshi-core/6.4.2' && cd 'compile/mvnc/com/github/oshi/oshi-core/6.4.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/oshi-core-6.4.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/oshi/oshi-core/6.4.2/target t || true ) )
# Set up deps for 2 generated test classes for com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/github/zafarkhaja/java-semver/0.9.0' && cd 'compile/mvnc/com/github/zafarkhaja/java-semver/0.9.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/github/zafarkhaja/java-semver/0.9.0/target t || true ) )
# Set up deps for 14 generated test classes for com/google/auto/auto-common/1.2.1/auto-common-1.2.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/auto/auto-common/1.2.1' && cd 'compile/mvnc/com/google/auto/auto-common/1.2.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/auto-common-1.2.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.1/target t || true ) )
# Set up deps for 6 generated test classes for com/google/auto/auto-common/1.2.2/auto-common-1.2.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/auto/auto-common/1.2.2' && cd 'compile/mvnc/com/google/auto/auto-common/1.2.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/auto-common/1.2.2/target t || true ) )
# Set up deps for 2 generated test classes for com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/auto/service/auto-service/1.0.1' && cd 'compile/mvnc/com/google/auto/service/auto-service/1.0.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/auto/service/auto-service/1.0.1/target t || true ) )
# Set up deps for 34 generated test classes for com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && cd 'compile/mvnc/com/google/guava/guava-testlib/32.1.2-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/guava-testlib-32.1.2-jre.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava-testlib/32.1.2-jre/target t || true ) )
# Set up deps for 320 generated test classes for com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/guava/guava/31.0.1-jre' && cd 'compile/mvnc/com/google/guava/guava/31.0.1-jre' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/target t || true ) )
# Set up deps for 2 generated test classes for com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/6.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/guice-assistedinject-6.0.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/6.0.0/target t || true ) )
# Set up deps for 2 generated test classes for com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-assistedinject/7.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/guice-assistedinject-7.0.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-assistedinject/7.0.0/target t || true ) )
# Set up deps for 6 generated test classes for com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-servlet/6.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-servlet/6.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/guice-servlet-6.0.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/6.0.0/target t || true ) )
# Set up deps for 6 generated test classes for com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/inject/extensions/guice-servlet/7.0.0' && cd 'compile/mvnc/com/google/inject/extensions/guice-servlet/7.0.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/guice-servlet-7.0.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/inject/extensions/guice-servlet/7.0.0/target t || true ) )
# Set up deps for 44 generated test classes for com/google/jimfs/jimfs/1.2/jimfs-1.2.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/jimfs/jimfs/1.2' && cd 'compile/mvnc/com/google/jimfs/jimfs/1.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/jimfs-1.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/jimfs/jimfs/1.2/target t || true ) )
# Set up deps for 32 generated test classes for com/google/truth/truth/1.1.3/truth-1.1.3.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/truth/truth/1.1.3' && cd 'compile/mvnc/com/google/truth/truth/1.1.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.3/truth-1.1.3.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.3/target t || true ) )
# Set up deps for 6 generated test classes for com/google/truth/truth/1.1.5/truth-1.1.5.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/truth/truth/1.1.5' && cd 'compile/mvnc/com/google/truth/truth/1.1.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.5/truth-1.1.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.1.5/target t || true ) )
# Set up deps for 6 generated test classes for com/google/truth/truth/1.2.0/truth-1.2.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/truth/truth/1.2.0' && cd 'compile/mvnc/com/google/truth/truth/1.2.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.2.0/truth-1.2.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/truth/truth/1.2.0/target t || true ) )
# Set up deps for 2 generated test classes for com/google/zxing/core/3.5.0/core-3.5.0.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.0' && cd 'compile/mvnc/com/google/zxing/core/3.5.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/core-3.5.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.0/target t || true ) )
# Set up deps for 2 generated test classes for com/google/zxing/core/3.5.1/core-3.5.1.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.1' && cd 'compile/mvnc/com/google/zxing/core/3.5.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/core-3.5.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.1/target t || true ) )
# Set up deps for 2 generated test classes for com/google/zxing/core/3.5.3/core-3.5.3.jar for mvnc
( mkdir -p 'compile/mvnc/com/google/zxing/core/3.5.3' && cd 'compile/mvnc/com/google/zxing/core/3.5.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/core-3.5.3.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/google/zxing/core/3.5.3/target t || true ) )
# Set up deps for 2 generated test classes for com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.jar for mvnc
( mkdir -p 'compile/mvnc/com/squareup/okhttp/okhttp/2.7.5' && cd 'compile/mvnc/com/squareup/okhttp/okhttp/2.7.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/okhttp-2.7.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/com/squareup/okhttp/okhttp/2.7.5/target t || true ) )
# Set up deps for 2 generated test classes for commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar for mvnc
( mkdir -p 'compile/mvnc/commons-configuration/commons-configuration/1.10' && cd 'compile/mvnc/commons-configuration/commons-configuration/1.10' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/target t || true ) )
# Set up deps for 2 generated test classes for commons-io/commons-io/2.14.0/commons-io-2.14.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.14.0' && cd 'compile/mvnc/commons-io/commons-io/2.14.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/commons-io-2.14.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.14.0/target t || true ) )
# Set up deps for 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.0' && cd 'compile/mvnc/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/target t || true ) )
# Set up deps for 10 generated test classes for commons-io/commons-io/2.15.0/commons-io-2.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.0' && cd 'compile/mvnc/commons-io/commons-io/2.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/commons-io-2.15.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.0/target t || true ) )
# Set up deps for 2 generated test classes for commons-io/commons-io/2.15.1/commons-io-2.15.1.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.15.1' && cd 'compile/mvnc/commons-io/commons-io/2.15.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/commons-io-2.15.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.15.1/target t || true ) )
# Set up deps for 2 generated test classes for commons-io/commons-io/2.16.0/commons-io-2.16.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-io/commons-io/2.16.0' && cd 'compile/mvnc/commons-io/commons-io/2.16.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/commons-io-2.16.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-io/commons-io/2.16.0/target t || true ) )
# Set up deps for 2 generated test classes for commons-logging/commons-logging/1.2/commons-logging-1.2.jar for mvnc
( mkdir -p 'compile/mvnc/commons-logging/commons-logging/1.2' && cd 'compile/mvnc/commons-logging/commons-logging/1.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.2/target t || true ) )
# Set up deps for 2 generated test classes for commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-logging/commons-logging/1.3.0' && cd 'compile/mvnc/commons-logging/commons-logging/1.3.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/commons-logging-1.3.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-logging/commons-logging/1.3.0/target t || true ) )
# Set up deps for 2 generated test classes for commons-net/commons-net/3.10.0/commons-net-3.10.0.jar for mvnc
( mkdir -p 'compile/mvnc/commons-net/commons-net/3.10.0' && cd 'compile/mvnc/commons-net/commons-net/3.10.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/commons-net-3.10.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/commons-net/commons-net/3.10.0/target t || true ) )
# Set up deps for 2 generated test classes for io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar for mvnc
( mkdir -p 'compile/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && cd 'compile/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/target t || true ) )
# Set up deps for 2 generated test classes for io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-buffer/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-buffer/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/netty-buffer-4.1.102.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.102.Final/target t || true ) )
# Set up deps for 6 generated test classes for io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-codec-http/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-codec-http/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/netty-codec-http-4.1.102.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.102.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty-codec/4.1.102.Final' && cd 'compile/mvnc/io/netty/netty-codec/4.1.102.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/netty-codec-4.1.102.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty-codec/4.1.102.Final/target t || true ) )
# Set up deps for 18 generated test classes for io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/netty/netty/3.10.6.Final' && cd 'compile/mvnc/io/netty/netty/3.10.6.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/target t || true ) )
# Set up deps for 84 generated test classes for io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.jar for mvnc
( mkdir -p 'compile/mvnc/io/rest-assured/rest-assured/5.2.1' && cd 'compile/mvnc/io/rest-assured/rest-assured/5.2.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/rest-assured/rest-assured/5.2.1/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.23.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.23.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.23.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.24.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.24.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.24.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.25.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.25.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.25.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.26.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.26.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.26.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.28.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.28.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.28.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.31.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.31.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.31.Final/target t || true ) )
# Set up deps for 4 generated test classes for io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.jar for mvnc
( mkdir -p 'compile/mvnc/io/undertow/undertow-servlet/2.2.32.Final' && cd 'compile/mvnc/io/undertow/undertow-servlet/2.2.32.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/io/undertow/undertow-servlet/2.2.32.Final/target t || true ) )
# Set up deps for 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for mvnc
( mkdir -p 'compile/mvnc/junit/junit/4.13.2' && cd 'compile/mvnc/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/target t || true ) )
# Set up deps for 2 generated test classes for junit/junit/4.13.2/junit-4.13.2.jar for mvnc
( mkdir -p 'compile/mvnc/junit/junit/4.13.2' && cd 'compile/mvnc/junit/junit/4.13.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/junit/junit/4.13.2/target t || true ) )
# Set up deps for 4 generated test classes for org/apache/avro/avro/1.11.1/avro-1.11.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/avro/avro/1.11.1' && cd 'compile/mvnc/org/apache/avro/avro/1.11.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/avro-1.11.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/avro/avro/1.11.1/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/commons/commons-configuration2/2.7' && cd 'compile/mvnc/org/apache/commons/commons-configuration2/2.7' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/commons/commons-configuration2/2.8.0' && cd 'compile/mvnc/org/apache/commons/commons-configuration2/2.8.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/commons-configuration2-2.8.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.8.0/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/curator/curator-recipes/5.6.0' && cd 'compile/mvnc/org/apache/curator/curator-recipes/5.6.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/curator-recipes-5.6.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/curator/curator-recipes/5.6.0/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8' && cd 'compile/mvnc/org/apache/cxf/cxf-rt-transports-http/3.5.8' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/cxf-rt-transports-http-3.5.8.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/cxf/cxf-rt-transports-http/3.5.8/target t || true ) )
# Set up deps for 12 generated test classes for org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5' && cd 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.5/target t || true ) )
# Set up deps for 12 generated test classes for org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6' && cd 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.3.6/target t || true ) )
# Set up deps for 28 generated test classes for org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0' && cd 'compile/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/3.4.0/target t || true ) )
# Set up deps for 10 generated test classes for org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5' && cd 'compile/mvnc/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/hadoop-mapreduce-client-core-3.3.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/3.3.5/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4' && cd 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/httpcore5-5.1.4.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.4/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5' && cd 'compile/mvnc/org/apache/httpcomponents/core5/httpcore5/5.1.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/httpcore5-5.1.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.5/target t || true ) )
# Set up deps for 2 generated test classes for org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/apache/logging/log4j/log4j-api/2.17.1' && cd 'compile/mvnc/org/apache/logging/log4j/log4j-api/2.17.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/target t || true ) )
# Set up deps for 2 generated test classes for org/codehaus/janino/janino/3.1.12/janino-3.1.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/codehaus/janino/janino/3.1.12' && cd 'compile/mvnc/org/codehaus/janino/janino/3.1.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/janino-3.1.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.12/target t || true ) )
# Set up deps for 2 generated test classes for org/codehaus/janino/janino/3.1.9/janino-3.1.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/codehaus/janino/janino/3.1.9' && cd 'compile/mvnc/org/codehaus/janino/janino/3.1.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/janino-3.1.9.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/codehaus/janino/janino/3.1.9/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.15.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.15.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/flyway-core-9.15.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.15.0/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.16.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.16.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/flyway-core-9.16.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.1/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.16.2' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.16.2' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/flyway-core-9.16.2.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.16.2/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.17.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.17.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/flyway-core-9.17.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.17.0/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.18.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.18.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/flyway-core-9.18.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.18.0/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/flyway-core-9.19.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.0/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/flyway-core-9.19.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.1/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.3' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/flyway-core-9.19.3.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.3/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.19.4' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.19.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/flyway-core-9.19.4.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.19.4/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.20.0' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.20.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/flyway-core-9.20.0.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.0/target t || true ) )
# Set up deps for 4 generated test classes for org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.20.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.20.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/flyway-core-9.20.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.20.1/target t || true ) )
# Set up deps for 2 generated test classes for org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/flywaydb/flyway-core/9.21.1' && cd 'compile/mvnc/org/flywaydb/flyway-core/9.21.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/flyway-core-9.21.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/flywaydb/flyway-core/9.21.1/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/target t || true ) )
# Set up deps for 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.37' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.37' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.37/target t || true ) )
# Set up deps for 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.38' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.38' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.38/target t || true ) )
# Set up deps for 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.39.1' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.39.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39.1/target t || true ) )
# Set up deps for 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.39' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.39' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.39/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.40' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.40' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.40/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.41' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/2.41' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/2.41/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.11' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.11' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.11/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.12/target t || true ) )
# Set up deps for 4 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.9' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-client/3.0.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-client/3.0.9/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.37' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.37' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.37/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.38' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.38' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.38/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.39.1' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.39.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39.1/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.39' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.39' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.39/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.40' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/2.40' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/2.40/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.10' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.10' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.10/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.11' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.11' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.11/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.9' && cd 'compile/mvnc/org/glassfish/jersey/core/jersey-server/3.0.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/3.0.9/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/inject/jersey-hk2/3.0.12/target t || true ) )
# Set up deps for 2 generated test classes for org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar for mvnc
( mkdir -p 'compile/mvnc/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && cd 'compile/mvnc/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/target t || true ) )
# Set up deps for 4 generated test classes for org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.jar for mvnc
( mkdir -p 'compile/mvnc/org/jfree/jfreechart/1.5.4' && cd 'compile/mvnc/org/jfree/jfreechart/1.5.4' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/jfreechart-1.5.4.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/jfree/jfreechart/1.5.4/target t || true ) )
# Set up deps for 4 generated test classes for org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.5' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/threetenbp-1.6.5.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.5/target t || true ) )
# Set up deps for 6 generated test classes for org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.6' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.6' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/threetenbp-1.6.6.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.6/target t || true ) )
# Set up deps for 6 generated test classes for org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.7' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.7' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/threetenbp-1.6.7.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.7/target t || true ) )
# Set up deps for 2 generated test classes for org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.8' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.8' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/threetenbp-1.6.8.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.8/target t || true ) )
# Set up deps for 4 generated test classes for org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.jar for mvnc
( mkdir -p 'compile/mvnc/org/threeten/threetenbp/1.6.9' && cd 'compile/mvnc/org/threeten/threetenbp/1.6.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/threetenbp-1.6.9.pom dependency:copy-dependencies >&2 && ( ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/repo1.maven.org/maven2/org/threeten/threetenbp/1.6.9/target t || true ) )
