#!/bin/bash
set -v
# Compile 2 generated test classes for com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.jar for gaoss
( mkdir -p 'compile/gaoss/com/google/auto/service/auto-service/1.0.1' && cd 'compile/gaoss/com/google/auto/service/auto-service/1.0.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/auto/service/auto-service/1.0.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/auto/service/auto-service/1.0.1/auto-service-1.0.1.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/auto/service/auto-service/1.0.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/com/google/auto/service/auto-service/1.0.1/evosuite-tests/com/google/auto/service/processor/*_ESTest*.java
)
# Compile 32 generated test classes for com/google/truth/truth/1.1.3/truth-1.1.3.jar for gaoss
( mkdir -p 'compile/gaoss/com/google/truth/truth/1.1.3' && cd 'compile/gaoss/com/google/truth/truth/1.1.3' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.3/truth-1.1.3.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.3/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.3/truth-1.1.3.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/truth/truth/1.1.3/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/com/google/truth/truth/1.1.3/evosuite-tests/com/google/common/truth/*_ESTest*.java
)
# Compile 6 generated test classes for com/google/truth/truth/1.1.5/truth-1.1.5.jar for gaoss
( mkdir -p 'compile/gaoss/com/google/truth/truth/1.1.5' && cd 'compile/gaoss/com/google/truth/truth/1.1.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.5/truth-1.1.5.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.1.5/truth-1.1.5.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/truth/truth/1.1.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/com/google/truth/truth/1.1.5/evosuite-tests/com/google/common/truth/*_ESTest*.java
)
# Compile 6 generated test classes for com/google/truth/truth/1.2.0/truth-1.2.0.jar for gaoss
( mkdir -p 'compile/gaoss/com/google/truth/truth/1.2.0' && cd 'compile/gaoss/com/google/truth/truth/1.2.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.2.0/truth-1.2.0.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.2.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/com/google/truth/truth/1.2.0/truth-1.2.0.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/com/google/truth/truth/1.2.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/com/google/truth/truth/1.2.0/evosuite-tests/com/google/common/truth/*_ESTest*.java
)
# Compile 18 generated test classes for io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/netty/netty/3.10.6.Final' && cd 'compile/gaoss/io/netty/netty/3.10.6.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/netty/netty/3.10.6.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/channel/socket/nio/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/channel/socket/oio/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/handler/codec/frame/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/handler/codec/marshalling/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/handler/ssl/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/util/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/netty/netty/3.10.6.Final/evosuite-tests/org/jboss/netty/util/internal/*_ESTest*.java
)
# Compile 84 generated test classes for io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.jar for gaoss
( mkdir -p 'compile/gaoss/io/rest-assured/rest-assured/5.2.1' && cd 'compile/gaoss/io/rest-assured/rest-assured/5.2.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/rest-assured/rest-assured/5.2.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/rest-assured/rest-assured/5.2.1/rest-assured-5.2.1.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/assertion/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/authentication/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/filter/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/http/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/mapping/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/matcher/xml/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/multipart/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/rest-assured/rest-assured/5.2.1/evosuite-tests/io/restassured/internal/support/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.23.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.23.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.23.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.23.Final/undertow-servlet-2.2.23.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.23.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.23.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.24.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.24.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.24.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.24.Final/undertow-servlet-2.2.24.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.24.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.24.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.25.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.25.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.25.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.25.Final/undertow-servlet-2.2.25.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.25.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.25.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.26.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.26.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.26.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.26.Final/undertow-servlet-2.2.26.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.26.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.26.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.28.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.28.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.28.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.28.Final/undertow-servlet-2.2.28.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.28.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.28.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.31.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.31.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.31.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.31.Final/undertow-servlet-2.2.31.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.31.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.31.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 4 generated test classes for io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.jar for gaoss
( mkdir -p 'compile/gaoss/io/undertow/undertow-servlet/2.2.32.Final' && cd 'compile/gaoss/io/undertow/undertow-servlet/2.2.32.Final' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.32.Final/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/io/undertow/undertow-servlet/2.2.32.Final/undertow-servlet-2.2.32.Final.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/undertow/undertow-servlet/2.2.32.Final/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/undertow/undertow-servlet/2.2.32.Final/evosuite-tests/io/undertow/servlet/spec/*_ESTest*.java
)
# Compile 12 generated test classes for org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.jar for gaoss
( mkdir -p 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.3.5' && cd 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.3.5' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.5/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.5/hadoop-hdfs-3.3.5.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5/evosuite-tests/org/apache/hadoop/hdfs/server/balancer/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5/evosuite-tests/org/apache/hadoop/hdfs/server/namenode/snapshot/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5/evosuite-tests/org/apache/hadoop/hdfs/tools/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.5/evosuite-tests/org/apache/hadoop/hdfs/tools/offlineImageViewer/*_ESTest*.java
)
# Compile 12 generated test classes for org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.jar for gaoss
( mkdir -p 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.3.6' && cd 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.3.6' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.6/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.3.6/hadoop-hdfs-3.3.6.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6/evosuite-tests/org/apache/hadoop/hdfs/server/balancer/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6/evosuite-tests/org/apache/hadoop/hdfs/server/namenode/snapshot/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6/evosuite-tests/org/apache/hadoop/hdfs/tools/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.3.6/evosuite-tests/org/apache/hadoop/hdfs/tools/offlineImageViewer/*_ESTest*.java
)
# Compile 28 generated test classes for org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.jar for gaoss
( mkdir -p 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.4.0' && cd 'compile/gaoss/org/apache/hadoop/hadoop-hdfs/3.4.0' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.4.0/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/apache/hadoop/hadoop-hdfs/3.4.0/hadoop-hdfs-3.4.0.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/protocol/proto/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/qjournal/protocol/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/server/balancer/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/server/namenode/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/server/namenode/ha/proto/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/server/namenode/snapshot/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/tools/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/apache/hadoop/hadoop-hdfs/3.4.0/evosuite-tests/org/apache/hadoop/hdfs/tools/offlineImageViewer/*_ESTest*.java
)
# Compile 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.37' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.37' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.37/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.37/jersey-client-2.37.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.37/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.37/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.37/evosuite-tests/org/glassfish/jersey/client/internal/jdkconnector/*_ESTest*.java
)
# Compile 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.38' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.38' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.38/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.38/jersey-client-2.38.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.38/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.38/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.38/evosuite-tests/org/glassfish/jersey/client/internal/jdkconnector/*_ESTest*.java
)
# Compile 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.39.1' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.39.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39.1/jersey-client-2.39.1.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39.1/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39.1/evosuite-tests/org/glassfish/jersey/client/internal/jdkconnector/*_ESTest*.java
)
# Compile 4 generated test classes for org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.39' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.39' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.39/jersey-client-2.39.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.39/evosuite-tests/org/glassfish/jersey/client/internal/jdkconnector/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.40' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.40' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.40/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.40/jersey-client-2.40.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.40/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.40/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.41' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/2.41' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.41/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/2.41/jersey-client-2.41.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.41/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/2.41/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.11' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.11' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.11/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.11/jersey-client-3.0.11.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.11/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.11/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.12' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java
)
# Compile 4 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.9' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-client/3.0.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.9/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-client/3.0.9/jersey-client-3.0.9.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.9/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.9/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.9/evosuite-tests/org/glassfish/jersey/client/internal/jdkconnector/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.37' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.37' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.37/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.37/jersey-server-2.37.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.37/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.37/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.38' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.38' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.38/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.38/jersey-server-2.38.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.38/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.38/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.39.1' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.39.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39.1/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39.1/jersey-server-2.39.1.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.39.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.39.1/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.39' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.39' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.39/jersey-server-2.39.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.39/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.39/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.40' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/2.40' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.40/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/2.40/jersey-server-2.40.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.40/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/2.40/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.10' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.10' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.10/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.10/jersey-server-3.0.10.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.10/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.10/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.11' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.11' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.11/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.11/jersey-server-3.0.11.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.11/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.11/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.12' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.jar for gaoss
( mkdir -p 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.9' && cd 'compile/gaoss/org/glassfish/jersey/core/jersey-server/3.0.9' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.9/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/google-aoss/org/glassfish/jersey/core/jersey-server/3.0.9/jersey-server-3.0.9.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.9/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.9/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
