#!/bin/bash
set -v
# Compile 2 generated test classes for io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/micronaut-kubernetes-discovery-client-3.4.1.jar for obfs
( mkdir -p 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && cd 'compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/micronaut-kubernetes-discovery-client-3.4.1-oracle-00001.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/maven.oracle.com/public/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1-oracle-00001/micronaut-kubernetes-discovery-client-3.4.1-oracle-00001.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1/evosuite-tests/io/micronaut/kubernetes/util/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/evosuite-tests/org/glassfish/jersey/netty/connector/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/evosuite-tests/org/glassfish/jersey/grizzly2/httpserver/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/evosuite-tests/org/glassfish/jersey/jdkhttp/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/evosuite-tests/org/glassfish/jersey/servlet/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/evosuite-tests/org/glassfish/jersey/servlet/init/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/evosuite-tests/org/glassfish/jersey/simple/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-client/3.0.12/evosuite-tests/org/glassfish/jersey/client/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/core/jersey-server/3.0.12/evosuite-tests/org/glassfish/jersey/server/internal/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/inject/jersey-hk2/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/inject/jersey-hk2/3.0.12/evosuite-tests/org/glassfish/jersey/inject/hk2/*_ESTest*.java
)
# Compile 2 generated test classes for org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar for obfs
( mkdir -p 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && cd 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12' && mvn -f /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.pom dependency:copy-dependencies >&2 && ln -sT /home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/target t
CLASSPATH=/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar:$(echo t/dependency/* | perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:testgen/mvnc/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/evosuite-tests:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar /usr/lib/jvm/java-8-openjdk-amd64/bin/javac -d . /home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/testgen/mvnc/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/evosuite-tests/org/glassfish/jersey/jaxb/internal/*_ESTest*.java
)
