#!/bin/bash
set -v
echo "Will write test results under RUNDIR=${RUNDIR:=run}"   # Default to 'run' if not overridden
# No compiled classes found for compile/obfs/ch/qos/logback/logback-access/1.3.11 so won't create ${RUNDIR}/obfs/ch/qos/logback/logback-access/1.3.11.
# No compiled classes found for compile/obfs/ch/qos/logback/logback-core/1.3.11 so won't create ${RUNDIR}/obfs/ch/qos/logback/logback-core/1.3.11.
# No compiled classes found for compile/obfs/com/google/guava/guava-testlib/32.1.2-jre so won't create ${RUNDIR}/obfs/com/google/guava/guava-testlib/32.1.2-jre.
# No compiled classes found for compile/obfs/commons-io/commons-io/2.15.0 so won't create ${RUNDIR}/obfs/commons-io/commons-io/2.15.0.
# No compiled classes found for compile/obfs/commons-logging/commons-logging/1.3.0 so won't create ${RUNDIR}/obfs/commons-logging/commons-logging/1.3.0.
# No compiled classes found for compile/obfs/commons-net/commons-net/3.10.0 so won't create ${RUNDIR}/obfs/commons-net/commons-net/3.10.0.
# No compiled classes found for compile/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1 so won't create ${RUNDIR}/obfs/io/micronaut/kubernetes/micronaut-kubernetes-discovery-client/3.4.1.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-budget/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-containerengine/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-core/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-fusionapps/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-identitydomains/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-loganalytics/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-opsi/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2 so won't create ${RUNDIR}/obfs/io/micronaut/oraclecloud/micronaut-oraclecloud-bmc-tenantmanagercontrolplane/3.0.2.
# No compiled classes found for compile/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5 so won't create ${RUNDIR}/obfs/io/micronaut/starter/micronaut-starter-api/3.8.5.
# No compiled classes found for compile/obfs/junit/junit/4.13.2 so won't create ${RUNDIR}/obfs/junit/junit/4.13.2.
# No compiled classes found for compile/obfs/org/apache/commons/commons-text/1.11.0 so won't create ${RUNDIR}/obfs/org/apache/commons/commons-text/1.11.0.
# No compiled classes found for compile/obfs/org/apache/zookeeper/zookeeper/3.9.1 so won't create ${RUNDIR}/obfs/org/apache/zookeeper/zookeeper/3.9.1.
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org/glassfish/jersey/netty/connector/LocalizationMessages_ESTest.class for org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/jersey-netty-connector-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/connectors/jersey-netty-connector/3.0.12/org.glassfish.jersey.netty.connector.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org/glassfish/jersey/grizzly2/httpserver/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/jersey-container-grizzly2-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-grizzly2-http/3.0.12/org.glassfish.jersey.grizzly2.httpserver.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org/glassfish/jersey/jdkhttp/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/jersey-container-jdk-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-jdk-http/3.0.12/org.glassfish.jersey.jdkhttp.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org/glassfish/jersey/servlet/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/jersey-container-servlet-core-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet-core/3.0.12/org.glassfish.jersey.servlet.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org/glassfish/jersey/servlet/init/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/jersey-container-servlet-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-servlet/3.0.12/org.glassfish.jersey.servlet.init.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org/glassfish/jersey/simple/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/jersey-container-simple-http-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/containers/jersey-container-simple-http/3.0.12/org.glassfish.jersey.simple.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org/glassfish/jersey/client/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-client/3.0.12/jersey-client-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.client.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org.glassfish.jersey.client.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-client/3.0.12/org.glassfish.jersey.client.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org/glassfish/jersey/server/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/core/jersey-server/3.0.12/jersey-server-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.server.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org.glassfish.jersey.server.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/core/jersey-server/3.0.12/org.glassfish.jersey.server.internal.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org/glassfish/jersey/inject/hk2/LocalizationMessages_ESTest.class for org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/inject/jersey-hk2/3.0.12/jersey-hk2-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/inject/jersey-hk2/3.0.12/org.glassfish.jersey.inject.hk2.LocalizationMessages_ESTest.err"
)
( mkdir -p "${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12" && cd 'compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12'
# Run compiled test class compile/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org/glassfish/jersey/jaxb/internal/LocalizationMessages_ESTest.class for org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar for obfs
CLASSPATH="/home/wtwhite/code/craw-redhat-oss/wget/crawl/bfs-dataset/maven-artifacts/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/jersey-media-jaxb-3.0.12.jar:$(echo t/dependency/*|perl -lpe 's/ /:/g'):/home/wtwhite/code/regression-test-generation/evosuite/evosuite-standalone-runtime-1.2.0.jar:.:/home/wtwhite/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/wtwhite/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" time /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java org.junit.runner.JUnitCore "org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest" > "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest.out" 2> "/home/wtwhite/code/regression-test-generation-NON-SOURCE-EQUIV/find-diff-classes/${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-jaxb/3.0.12/org.glassfish.jersey.jaxb.internal.LocalizationMessages_ESTest.err"
)
# No compiled classes found for compile/obfs/org/glassfish/jersey/media/jersey-media-sse/3.0.12 so won't create ${RUNDIR}/obfs/org/glassfish/jersey/media/jersey-media-sse/3.0.12.
# No compiled classes found for compile/obfs/org/slf4j/slf4j-simple/2.0.9 so won't create ${RUNDIR}/obfs/org/slf4j/slf4j-simple/2.0.9.
